source/main.tf
=> Setting version for VPC module

helm/aws-for-fluent-bit/README.md, helm/aws-for-fluent-bit/main.tf, helm/aws-for-fluent-bit/variables.tf, helm/helm.tf, helm/variables.tf, live/preprod/eu-west-1/application/dev/base.tfvars, source/main.tf, source/variables.tf
2
aws-for-fluent-bit updated with helm chart version 0.1.11
=> aws-for-fluent-bit updated with helm chart version 0.1.11

README.md, deploy/live/preprod/eu-west-1/application/dev/dev.tfvars, deploy/live/preprod/eu-west-1/application/test/test.tfvars, deploy/live/preprod/eu-west-1/gaming/test/base.tfvars, examples/aws-lb-ingress-controller/eks-with-lb-ingress.tfvars, examples/windows-support/eks-with-windows-support.tfvars, kuberenets-addons.tf, kuberenets-addons/kuberenets-addons.tf, kuberenets-addons/opentelemetry-collector/main.tf, kuberenets-addons/variables.tf, modules/aws-eks-addon/main.tf, modules/aws-eks-fargate-profiles/aws-eks-fargate.tf, modules/aws-eks-fargate-profiles/iam.tf, modules/aws-eks-fargate-profiles/outputs.tf, modules/aws-eks-managed-node-groups/iam.tf, outputs.tf, variables.tf
=> Readme updated with the new module version and features

README.md, deploy/eks-cluster-with-new-vpc/main.tf, docs/Advanced/cluster-upgrades.md, docs/core-concepts.md, docs/getting-started.md, docs/node-groups.md
=> README update with corrections

docs/modules/emr-on-eks.md, locals.tf, modules/emr-on-eks/locals.tf, modules/emr-on-eks/main.tf
=> emr on eks fix for service account

README.md, aws-auth-configmap.tf, deploy/advanced/live/preprod/eu-west-1/application_acct/dev/README.md, deploy/advanced/live/preprod/eu-west-1/application_acct/dev/main.tf, deploy/eks-cluster-with-new-vpc/README.md, deploy/eks-cluster-with-new-vpc/main.tf, docs/add-ons/keda.md, kubernetes-addons.tf, kubernetes-addons/agones/README.md, kubernetes-addons/fargate-fluentbit/fargate_fluentbit_cw.tf, kubernetes-addons/irsa/README.md, kubernetes-addons/irsa/data.tf, kubernetes-addons/irsa/locals.tf, kubernetes-addons/irsa/main.tf, kubernetes-addons/irsa/outputs.tf, kubernetes-addons/irsa/variables.tf, kubernetes-addons/keda/README.md, kubernetes-addons/keda/keda-default-iam-policy.json, kubernetes-addons/keda/keda-values.yaml, kubernetes-addons/keda/locals.tf, kubernetes-addons/keda/main.tf, kubernetes-addons/keda/variables.tf, variables.tf
=> Added KEDA helm addon for Kubernetes-based Event Driven Autoscaler

variables.tf
=> Fix description of public_subnet_ids

variables.tf
=> Fix description of var.enable_managed_nodegroups

README.md, aws-eks-worker.tf, deploy/advanced/live/preprod/eu-west-1/application_acct/dev/main.tf, deploy/eks-cluster-with-new-vpc/main.tf, docs/add-ons/index.md, docs/core-concepts.md, docs/node-groups.md, kubernetes-addons.tf, kubernetes-addons/argocd/argocd-application/templates/application.yaml, kubernetes-addons/argocd/argocd-application/values.yaml, kubernetes-addons/argocd/main.tf, locals.tf, modules/aws-eks-fargate-profiles/README.md, modules/aws-eks-managed-node-groups/README.md, modules/aws-eks-managed-node-groups/variables.tf, modules/aws-eks-self-managed-node-groups/README.md, modules/aws-eks-self-managed-node-groups/variables.tf, outputs.tf, variables.tf
=> remove unnecessary use of boolean variables to enable workers

README.md
=> add pre-prod msg

.github/test/e2e/README.md, .github/test/pr/README.md, kubernetes-addons/yunikorn/locals.tf
=> pre-commit format fix

kubernetes-addons/aws-node-termination-handler/main.tf, kubernetes-addons/keda/main.tf, modules/aws-eks-addon/aws-ebs-csi-driver/main.tf, modules/aws-eks-addon/vpc-cni/main.tf, modules/irsa/README.md, modules/irsa/data.tf, modules/irsa/main.tf, modules/irsa/outputs.tf, modules/irsa/variables.tf
*Issue #105 , if available:*
- IRSA module updates with conditional service account create
- Updated variables to match Terraform Kubernetes resources 
=> Hotfix vpc cni

docs/Advanced/gitops-with-flux.md
As per discussion with @kcaws , this PR adds documentation to bootstrap EKS clusters configuration with Flux using a sample repository. 
=> Add Flux documentation

kubernetes-addons/fargate-fluentbit/ main.tf, kubernetes-addons/fargate-fluentbit/README.md, kubernetes-addons/fargate-fluentbit/locals.tf, test/e2e/vpc/main.tf, test/pr/README.md
=> refactor var names for fargate-fluentbit

kubernetes-addons/agones/locals.tf, kubernetes-addons/argocd/locals.tf
=> agones & argocd - default_helm_values local name

kubernetes-addons/cluster-autoscaler/README.md, kubernetes-addons/cluster-autoscaler/locals.tf, kubernetes-addons/cluster-autoscaler/main.tf, kubernetes-addons/cluster-autoscaler/variables.tf
=> refactor var names for cluster-autoscaler

.github/workflows/pr-test.yml, kubernetes-addons.tf, kubernetes-addons/aws-node-termination-handler/locals.tf, kubernetes-addons/aws-node-termination-handler/main.tf, kubernetes-addons/aws-node-termination-handler/variables.tf, kubernetes-addons/aws-opentelemetry-eks/locals.tf, kubernetes-addons/aws-opentelemetry-eks/main.tf, kubernetes-addons/aws-opentelemetry-eks/variables.tf
=> Updating add-ons

.github/workflows/pr-test.yml, kubernetes-addons.tf, kubernetes-addons/aws-for-fluentbit/locals.tf, kubernetes-addons/aws-load-balancer-controller/locals.tf, kubernetes-addons/aws-load-balancer-controller/main.tf, kubernetes-addons/aws-load-balancer-controller/outputs.tf, kubernetes-addons/aws-opentelemetry-eks/variables.tf
=> Fixing formatting

kubernetes-addons.tf, kubernetes-addons/cert-manager/README.md, kubernetes-addons/cert-manager/locals.tf, kubernetes-addons/cert-manager/main.tf, kubernetes-addons/cert-manager/variables.tf
=> refactor var names for cert-manager

kubernetes-addons/aws-for-fluentbit/README.md, kubernetes-addons/aws-load-balancer-controller/README.md, kubernetes-addons/aws-node-termination-handler/README.md, kubernetes-addons/aws-opentelemetry-eks/README.md, kubernetes-addons/aws-opentelemetry-eks/variables.tf, kubernetes-addons/ingress-nginx/README.md, kubernetes-addons/keda/README.md
=> Fix terraform fmt

.github/workflows/tflint.yaml
=> renamed tflint workflow

.github/workflows/e2e-test-cleanup.yml, .github/workflows/vpc-test-cleanup.yml
=> add cleanup jobs

kubernetes-addons.tf, kubernetes-addons/fargate-fluentbit/locals.tf, kubernetes-addons/fargate-fluentbit/variables.tf
=> fix variable name for addon_config

deploy/2-eks-cluster-with-import-vpc/eks/main.tf
temp disabling vpa,prometheus and nginx addons in e2e 
=> test: disable vpa,prometheus and nginx addons e2e

README.md, deploy/1-eks-cluster-with-new-vpc/main.tf, deploy/2-eks-cluster-with-import-vpc/eks/main.tf, deploy/advanced/k8s_addons/main.tf, deploy/advanced/live/preprod/eu-west-1/application_acct/dev/main.tf, docs/add-ons/agones.md, docs/add-ons/argocd.md, docs/add-ons/aws-for-fluent-bit.md, docs/add-ons/aws-load-balancer-controller.md, docs/add-ons/aws-node-termination-handler.md, docs/add-ons/index.md, docs/add-ons/managed-add-ons.md, docs/add-ons/prometheus.md, docs/add-ons/spark-k8s-operator.md, docs/add-ons/vertical-pod-autoscaler.md, docs/add-ons/yunikorn.md, docs/advanced/cluster-upgrades.md, docs/modules/emr-on-eks.md, kubernetes-addons/main.tf, kubernetes-addons/variables.tf, modules/aws-eks-self-managed-node-groups/README.md
- Docs update for k8s add-ons
- renamed eks add-on variables to match Amazon naming convention
=> Docs for k8s addon refactor

.github/workflows/e2e-test.yml, deploy/2-eks-cluster-with-import-vpc/eks/main.tf
=> test: e2e new local names, tf destroy if apply failed

test/e2e/eks/main.tf
=> test: change env name

.github/workflows/e2e-test.yml
=> increase role duration to 2 hours

.github/workflows/e2e-test.yml, deploy/2-eks-cluster-with-import-vpc/eks/main.tf
=> test: disable vpa/prom/nginx, role timeout 30 mins

deploy/2-eks-cluster-with-import-vpc/eks/main.tf
add aws provider alias name to k8s addons module
=> test: e2e add provider aws alias

deploy/2-eks-cluster-with-import-vpc/eks/main.tf
=> test: e2e aws_region name instead of id

deploy/2-eks-cluster-with-import-vpc/eks/main.tf
=> test: e2e eks aws provider to us-west-2

test/e2e/eks/main.tf
=> test: e2e tenant/env/zone original names

deploy/2-eks-cluster-with-import-vpc/eks/main.tf
=> test: e2e temp disable fargate fluentbit

.github/workflows/e2e-test.yml
- add input to e2e test, can skip running TF destroy if needed for troubleshooting purposes
=> test: e2e tf destroy input

deploy/2-eks-cluster-with-import-vpc/eks/main.tf
=> Simplifying e2e for the time being

README.md, deploy/1-eks-cluster-with-new-vpc/main.tf
- README Update
- Example1 update with correct dependency
=> Readme update

.github/workflows/e2e-test-cleanup.yml
- E2E test cleanup Github Workflow update
=> e2e test cleanup fix with correct backendconf and tfvars

examples/5-eks-cluster-with-windows-support/README.md, examples/5-eks-cluster-with-windows-support/k8s/linux-nginx.yaml, examples/5-eks-cluster-with-windows-support/k8s/windows-iis-aspnet.yaml, examples/5-eks-cluster-with-windows-support/main.tf
https://github.com/aws-ia/terraform-ssp-amazon-eks/issues/145
Updated Windows support example per the latest code changes such as renaming of variables and moved it to this repo from the patterns repo. Tested by following the instructions in README.
=> Updated Windows support example

.github/workflows/e2e-test-cleanup.yml, .github/workflows/e2e-test.yml
=> test: increasr role duration to 1h e2e-test

README.md, docs/add-ons/aws-for-fluent-bit.md, examples/1-eks-cluster-with-new-vpc/README.md, main.tf, modules/aws-eks-managed-node-groups/README.md, modules/aws-eks-managed-node-groups/data.tf, modules/aws-eks-managed-node-groups/iam.tf, modules/aws-eks-self-managed-node-groups/README.md, modules/aws-eks-self-managed-node-groups/data.tf, modules/aws-eks-self-managed-node-groups/iam.tf, modules/aws-kms/README.md, modules/kubernetes-addons/README.md, modules/kubernetes-addons/aws-for-fluentbit/README.md, modules/kubernetes-addons/aws-for-fluentbit/data.tf, modules/kubernetes-addons/aws-for-fluentbit/locals.tf, modules/kubernetes-addons/aws-for-fluentbit/main.tf, modules/kubernetes-addons/aws-for-fluentbit/outputs.tf, modules/kubernetes-addons/aws-for-fluentbit/values.yaml, modules/kubernetes-addons/aws-for-fluentbit/variables.tf, modules/kubernetes-addons/main.tf, modules/kubernetes-addons/variables.tf
- IRSA for AWS For Fluent Bit
- Removed Node level roles 
- Docs updated
=> IRSA for AWS for Fluent Bit Add-on

examples/6-eks-fully-private-eks-cluster/README.md, examples/6-eks-fully-private-eks-cluster/main.tf
- added cluster endpoints settings to the private example
-  fixed docs, explaining how to access the private endpoint
=> test: add cluster endpoints settings, fix docs

examples/6-eks-cluster-with-argocd/main.tf, modules/kubernetes-addons/argocd/variables.tf
=> Updating add-ons url

modules/kubernetes-addons/aws-node-termination-handler/main.tf
Enable SSE encryption by default.
=> add SSE encryption for SQS

.github/workflows/kics-security-scan.yml
- KICS GitHub Action workflow added for PRs and Merge to Main
**What is KICS?**
*Kicscan is an open source solution for static code analysis of Infrastructure as Code. With KICS, finding security vulnerabilities, compliance issues, and infrastructure misconfigurations happens early in the development cycle, when fixing these is straightforward and cheap*
=> KICS Security Scan Github Action Workflow

examples/game_tech/agones-game-controller/main.tf
- correcting local name to `cluster_name`
- managed node group to have public ips on public subnet for agones example
=> fix: agones example public ip to true

.github/workflows/kics-security-scan.yml, docs/add-ons/argocd.md, examples/karpenter/main.tf, examples/karpenter/provisioners/default_provisioner_with_launch_templates.yaml, modules/kubernetes-addons/argocd/data.tf
- Karpenter example fix 
- Pre-commit formatting
=> karpenter example hot fix

modules/launch-templates/README.md
=> Fix broken link to example

docs/add-ons/crossplane.md, docs/add-ons/karpenter.md
- Docs Update for Karpenter and Crossplane
=> Docs update

examples/observability/eks-cluster-with-amp-amg-opensearch/README.md, modules/kubernetes-addons/argocd/README.md, modules/kubernetes-addons/argocd/data.tf, modules/kubernetes-addons/argocd/main.tf
Fixes #235 
ArgoCD example should work now.
=> fix for argocd error when ssh_key_secret_name is not provided

examples/analytics/emr-on-eks/README.md, examples/analytics/emr-on-eks/main.tf, modules/aws-managed-prometheus/locals.tf
- Prometheus and VPA version update for examples
=> Prometheus and VPA version update for examples

examples/eks-cluster-with-windows-support/README.md, modules/aws-eks-managed-node-groups/README.md, modules/aws-eks-managed-node-groups/variables.tf, modules/aws-eks-self-managed-node-groups/README.md, modules/aws-eks-self-managed-node-groups/variables.tf, modules/launch-templates/locals.tf
- Security fix for HTTP TOKENS
=> Fixed http tokens for launch templates

.github/workflows/kics-security-scan.yml
=> KICS for PR and merge to main

examples/analytics/emr-on-eks/examples/spark-execute/5-spark-job-with-AMP-AMG.sh
- Format update for example 
- Fix added for driver metrics
=> EMR on EKS Prometheus app configuration for Spark driver and executor

modules/kubernetes-addons/README.md, modules/kubernetes-addons/keda/README.md, modules/kubernetes-addons/keda/locals.tf, modules/kubernetes-addons/keda/main.tf, modules/kubernetes-addons/keda/outputs.tf, modules/kubernetes-addons/keda/values.yaml, modules/kubernetes-addons/keda/variables.tf, modules/kubernetes-addons/main.tf, modules/kubernetes-addons/variables.tf
Refactors keda addon to use helm-addon
Consistency of addons
=> refactor keda for helm-addon

modules/kubernetes-addons/aws-load-balancer-controller/README.md, modules/kubernetes-addons/aws-load-balancer-controller/locals.tf, modules/kubernetes-addons/aws-load-balancer-controller/main.tf, modules/kubernetes-addons/aws-load-balancer-controller/outputs.tf, modules/kubernetes-addons/aws-load-balancer-controller/variables.tf
- Refactor lb-controller addon to use helm-addon module
- Remove copyright descriptions
=> refactor: lb-controller to use helm-addon module

modules/kubernetes-addons/README.md, modules/kubernetes-addons/aws-node-termination-handler/README.md, modules/kubernetes-addons/aws-node-termination-handler/data.tf, modules/kubernetes-addons/aws-node-termination-handler/locals.tf, modules/kubernetes-addons/aws-node-termination-handler/main.tf, modules/kubernetes-addons/aws-node-termination-handler/variables.tf, modules/kubernetes-addons/main.tf, modules/kubernetes-addons/variables.tf
- Refactor node-termination addon to use helm-addon module
- Remove copyright descriptions
=> refactor: node-termination to use helm-addon module

.github/workflows/e2e-all-tests-parallel.yml
=> fix: remove old folder argocd example

examples/windows-node-groups/README.md, examples/windows-node-groups/main.tf
=> fix: use local source path for example

examples/ingress-controllers/nginx/README.md, examples/ingress-controllers/nginx/main.tf
=> fix: use local source instead of git

modules/kubernetes-addons/aws-for-fluentbit/README.md, modules/kubernetes-addons/aws-for-fluentbit/locals.tf, modules/kubernetes-addons/aws-for-fluentbit/main.tf, modules/kubernetes-addons/aws-for-fluentbit/variables.tf
=> refactor: aws-for-fluent to use helm-addon module

main.tf
=> org value was missing in tags

docs/index.md, docs/node-groups.md, examples/ci-cd/gitlab-ci-cd/.gitlab-ci.yml
- Updated to docs to show how to add additional IAM roles, users and accounts using EKS Blueprints module
- This was requested by customers and users.
=> Updated docs for adding additional IAM roles, users and accounts to aws-auth

.github/workflows/e2e-terratest.yml, .github/workflows/plan-examples.yml, .github/workflows/pre-commit.yaml, README.md, docs/advanced/cluster-upgrades.md, docs/getting-started.md, docs/index.md
- Remove GitHub actions workflow badges from main README
- Update `cluster-upgrades` guide to remove managed CNI versions 
- Replace green check icons with simple markdown unordered list
- These actions are no longer present on the repository
- Kubernetes versions shown are outdated and keeping the addon version table up to date will be problematic
- Ensure list formatting is preserved
=> chore: Update documentation formatting

README.md
- Fix list of provisioned resources formatting
=> chore: Correct list of provisioned resources formatting

modules/kubernetes-addons/external-dns/locals.tf, modules/kubernetes-addons/locals.tf
=> fix(addons): fixes gitops error when enable_external_dns=true

.github/workflows/plan-examples.yml
- More notes 
- Explicit checkout 
- Adds more notes around security concerns using `pull_request_target` for future maintainers.
- Explicit checkout PR code as pull_request_target changes checkout behavior to default to source main.
=> fix: checkout correct code, more notes

examples/aws-efs-csi-driver/README.md
Documentation update only.
I had created the example a while back and I was testing it again today.
```
aws-efs-csi-driver % kubectl exec efs-app -- bash -c "cat data/out"
Wed Jun 8 13:57:31 UTC 2022
Wed Jun 8 13:57:36 UTC 2022
```
=> Comment on region in main.tf and fix cluster name

docs/extensibility.md
=> Document how to provide a custom helm-addon

examples/stateful/main.tf
=> fix: v1alpha1 -> v1beta1

examples/observability/adot-amp-grafana-for-nginx/main.tf
Updated with proper indenting for rules
Update main.tf with proper indenting for prometheus rules
- [x ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [x ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ x] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [x ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x ] Yes, I ran `pre-commit run -a` with this PR
=> Update main.tf with proper indenting

data.tf, examples/analytics/emr-on-eks/main.tf, modules/aws-eks-fargate-profiles/main.tf, modules/aws-eks-self-managed-node-groups/data.tf, modules/aws-eks-teams/data.tf, modules/kubernetes-addons/aws-ebs-csi-driver/main.tf, modules/kubernetes-addons/aws-for-fluentbit/data.tf, modules/kubernetes-addons/aws-load-balancer-controller/data.tf, modules/kubernetes-addons/aws-node-termination-handler/data.tf, modules/kubernetes-addons/aws-privateca-issuer/data.tf, modules/kubernetes-addons/aws-vpc-cni/main.tf, modules/kubernetes-addons/cluster-autoscaler/main.tf, modules/kubernetes-addons/crossplane/data.tf, modules/kubernetes-addons/external-dns/data.tf, modules/kubernetes-addons/keda/data.tf, modules/kubernetes-addons/prometheus/main.tf, modules/kubernetes-addons/velero/main.tf
Signed-off-by: Fernando Miguel <github@FernandoMiguel.net>
Sorts IAM block actions alphabetically
=> chore: Sort IAM policy actions alphabetically

examples/tls-with-aws-pca-issuer/README.md
Fixes clone link the ACM PCA example readme.
Old link referring to eks-acclerator.
=> fix(example): update link in the acm pca example

examples/ipv4-prefix-delegation/README.md, examples/ipv4-prefix-delegation/main.tf, examples/ipv4-prefix-delegation/outputs.tf, examples/ipv4-prefix-delegation/variables.tf, examples/ipv4-prefix-delegation/versions.tf, modules/aws-eks-managed-node-groups/templates/userdata-amazonlinux2eks.tpl
- Add new example demonstrating how to configure prefix delegation to increase the amount of available IP address
- Update EKS managed node groups AL2 userdata to render templates in terraform and remove logic not used in rendered userdata from what is sent to the launch template. This keeps the userdata cleaner (there are size restrictions) and only to what is in use by the current settings 
- Demonstrate how users can enable https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html to better utilize the available IP space
=> feat: Add new example demonstrating how to configure prefix delegation to increase the amount of available IP address

.github/workflows/markdown-link-check.yml, docs/add-ons/spark-history-server.md, examples/analytics/spark-k8s-operator/main.tf, modules/kubernetes-addons/README.md, modules/kubernetes-addons/locals.tf, modules/kubernetes-addons/main.tf, modules/kubernetes-addons/spark-history-server/README.md, modules/kubernetes-addons/spark-history-server/locals.tf, modules/kubernetes-addons/spark-history-server/main.tf, modules/kubernetes-addons/spark-history-server/outputs.tf, modules/kubernetes-addons/spark-history-server/values.yaml, modules/kubernetes-addons/spark-history-server/variables.tf, modules/kubernetes-addons/spark-history-server/versions.tf, modules/kubernetes-addons/variables.tf
- 🎇  Spark WebUI Add-on (Spark history Server Helm Chart)
- 📜 Docs added
=> 🚀  Spark history server add-on

examples/fully-private-eks-cluster/README.md
Added additional detail about how to create and assign an IAM role to the Cloud9 instance
see also: https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/824#issuecomment-1212908766
Clarifies the deployment steps in the example [Fully Private Cluster](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/fully-private-eks-cluster)
To help others avoid the mistake I made in not understanding how to assign an IAM role.
=> Clarifying deployment steps (assign IAM role) in the example Fully Private Cluster

modules/kubernetes-addons/argocd/main.tf
Just corrected repoUrl.
https://github.com/aws-samples/eks-blueprints-add-ons/blob/main/chart/values.yaml#L2
=> fix: corrected repoUrl.

docs/add-ons/external-secrets.md, modules/kubernetes-addons/external-secrets/locals.tf
=> chore: patch external-secrets version

modules/kubernetes-addons/locals.tf
=> Add image uri for Jakarta region 🌾

docs/add-ons/smb-csi-driver.md, modules/kubernetes-addons/README.md, modules/kubernetes-addons/locals.tf, modules/kubernetes-addons/main.tf, modules/kubernetes-addons/smb-csi-driver/README.md, modules/kubernetes-addons/smb-csi-driver/locals.tf, modules/kubernetes-addons/smb-csi-driver/main.tf, modules/kubernetes-addons/smb-csi-driver/outputs.tf, modules/kubernetes-addons/smb-csi-driver/variables.tf, modules/kubernetes-addons/smb-csi-driver/versions.tf, modules/kubernetes-addons/variables.tf
=> feat: Add smb-csi-driver to Kubernetes addon

docs/add-ons/chaos-mesh.md, modules/kubernetes-addons/README.md, modules/kubernetes-addons/chaos-mesh/README.md, modules/kubernetes-addons/chaos-mesh/locals.tf, modules/kubernetes-addons/chaos-mesh/main.tf, modules/kubernetes-addons/chaos-mesh/outputs.tf, modules/kubernetes-addons/chaos-mesh/variables.tf, modules/kubernetes-addons/chaos-mesh/versions.tf, modules/kubernetes-addons/locals.tf, modules/kubernetes-addons/main.tf, modules/kubernetes-addons/variables.tf
=> feat: Add chaos-mesh to Kubernetes addon

examples/reinvent-demo/core-services/limit-range.yaml, examples/reinvent-demo/main.tf
Updating sample to include Application and Platform team walkthrough and simple deployment
Updating sample to include Application and Platform team walkthrough and simple deployment
- [X ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
=> feat: Adding platform and application teams configurations and example

modules/kubernetes-addons/appmesh-controller/main.tf
=> fix: Create appmesh-system namespace

examples/karpenter/README.md
- Fixing a simple Typo in Readme.md 
- Fixing a simple typo in Readme
=> fix: Update README.md

docs/add-ons/apache-airflow.md
- fixes broken links for Airflow doc
=> chore: Airflow broken links updated

examples/reinvent-demo/main.tf
- adds WS participant role to cluster aws-auth
- wait for fargate for app2048
- teams output for platform and app team
=> fix: add ws role, wait for fargate, teams output

modules/aws-eks-managed-node-groups/managed-launch-templates.tf
=> fix: Add tags to managed node group launch template

docs/add-ons/aws-load-balancer-controller.md
highlight in the documentation how to bypass the IRSA too long error with LBC
=> docs: Demonstrate how to bypass IRSA name length

FAQ.md, docs/add-ons/grafana.md, docs/add-ons/portworx.md, docs/advanced/gitops-with-flux.md, docs/extensibility.md, docs/node-groups.md, examples/analytics/emr-eks-fsx-lustre/README.md, examples/fully-private-eks-cluster/README.md, examples/karpenter/README.md, examples/node-groups/managed-node-groups/README.md, examples/observability/adot-amp-grafana-for-haproxy/README.md, examples/observability/adot-amp-grafana-for-java/README.md, examples/observability/adot-amp-grafana-for-memcached/README.md, examples/observability/adot-amp-grafana-for-nginx/README.md, examples/upgrade/blue-green-route53/README.md, examples/upgrade/blue-green-route53/core-infra/README.md, examples/upgrade/blue-green-route53/core-infra/main.tf, examples/upgrade/blue-green-route53/modules/eks_cluster/README.md, examples/upgrade/blue-green-route53/modules/eks_cluster/main.tf, examples/wireguard-with-cilium/README.md, modules/aws-eks-self-managed-node-groups/README.md, modules/aws-eks-self-managed-node-groups/outputs.tf, modules/kubernetes-addons/README.md, modules/kubernetes-addons/cilium/README.md, modules/kubernetes-addons/cilium/variables.tf, modules/kubernetes-addons/traefik/README.md, modules/kubernetes-addons/variables.tf
Signed-off-by: Fernando Miguel <github@FernandoMiguel.net>
fix docs typos 
=> docs: Fix typos

modules/kubernetes-addons/karpenter/locals.tf
Update karpenter to [v0.22.0](https://github.com/aws/karpenter/releases/tag/v0.22.0)
Improvements and fixes.
=> feat: Update Karpenter to 0.22.0

docs/add-ons/grafana.md
fix grafana docs typo karpenter_helm_config -> grafana_helm_config
=> docs: Fix typo grafana helm config

modules/kubernetes-addons/aws-node-termination-handler/locals.tf
=> fix: Add aws-node-termination-handler.argocd_gitops_config.queueURL

docs/add-ons/karpenter.md
Just adds a missing word :slightly_smiling_face: 
Unless "visiting the karpenter" is an inside joke I've missed :sweat_smile:
=> docs: Add missing word

docs/add-ons/secrets-store-csi-driver.md
=> docs: Add helm configuration example to `secrets-store-csi-driver`

examples/agones-game-controller/main.tf, examples/amp-amg-opensearch/main.tf, examples/appmesh-mtls/main.tf, examples/argocd/main.tf, examples/blue-green-upgrade/core-infra/main.tf, examples/external-secrets/main.tf, examples/fargate-serverless/main.tf, examples/fully-private-cluster/main.tf, examples/ipv4-prefix-delegation/main.tf, examples/ipv6-eks-cluster/main.tf, examples/karpenter/main.tf, examples/multi-tenancy-with-teams/main.tf, examples/stateful/main.tf, examples/tls-with-aws-pca-issuer/main.tf, examples/vpc-cni-custom-networking/main.tf, examples/wireguard-with-cilium/main.tf
- Update VPC module to v4, update EKS module to latest minor version
- The VPC module v4 was just released which simplifies the default settings
=> chore: Update VPC module to v4, update EKS module to latest minor version

modules/aws-eks-self-managed-node-groups/self-managed-launch-templates.tf
Fixed spot instance bug in self managed node group
- Resolves #1539
=> fix: Fix spot instance issue in self managed node group template

examples/do-not-use/docs/aws-efs-csi-driver.md, examples/do-not-use/docs/velero.md, examples/stateful/README.md, examples/stateful/main.tf, examples/stateful/outputs.tf
Validate velero, efs, and stateful example
=> chore: Validate velero, efs, and stateful example

examples/ipv4-prefix-delegation/README.md, examples/ipv4-prefix-delegation/main.tf
update ipv4-prefix-delegation example
=> feat: Update ipv4-prefix-delegation example

examples/argocd/README.md, examples/argocd/main.tf, examples/argocd/outputs.tf, examples/argocd/versions.tf
=> fix(chore): Argo example update

examples/do-not-use/docs/aws-cloudwatch-metrics.md, examples/do-not-use/main.tf
updates docs for aws-cloudwatch-metrics
Updates while testing
=> feat: Update aws-cloudwatch-metrics module

examples/blue-green-upgrade/README.md
=> fix: Update blue/green example docs

.github/scripts/plan-examples.py, docs/v4-to-v5/addons.md, docs/v4-to-v5/example/v4.tf, docs/v4-to-v5/example/v5.tf, docs/v4-to-v5/teams.md, examples/agones-game-controller/main.tf, examples/appmesh-mtls/main.tf, examples/argocd/main.tf, examples/blue-green-upgrade/environment/main.tf, examples/blue-green-upgrade/modules/eks_cluster/main.tf, examples/elastic-fabric-adapter/main.tf, examples/external-secrets/main.tf, examples/fargate-serverless/main.tf, examples/karpenter/main.tf, examples/multi-tenancy-with-teams/main.tf, examples/stateful/main.tf, examples/tls-with-aws-pca-issuer/main.tf
- Update versions used to reflect v1.0 modules released
- Reflect v1.0 releases
=> chore: Update versions used to reflect v1.0 modules released

v4.32.1/teams/index.html
=> Added the right link for aws-team

examples/istio/README.md
=> docs: Added additional info to README.md of Istio example

patterns/istio/README.md
Added a `terraform init` to README.md for Istio pattern.
=> docs: Added command to initialize the Terraform repo

docs/patterns/karpenter.md, docs/patterns/kubecost.md, patterns/kubecost/run-me-in-24h/main.tf
=> docs: Adding Kubecost on `docs/patterns`

README.md
=> chore: Update README.md for karpenter-blueprints reference

docs/patterns/vpc-lattice.md, docs/patterns/vpc-lattice/cross-cluster-pod-communication.md, patterns/vpc-lattice/README.md
=> fix: Link to vpc lattice doc

docs/patterns/machine-learning/aws-neuron-efa.md, patterns/aws-neuron-efa/README.md, patterns/aws-neuron-efa/eks.tf, patterns/aws-neuron-efa/helm.tf, patterns/aws-neuron-efa/main.tf
- Add pattern for Neuron using Trainium and new AL2023 Neuron AMI
- AWS Neuron equivalent of the NVIDIA w/ EFA pattern
=> feat: Add pattern for Neuron using Trainium and new AL2023 Neuron AMI

.pre-commit-config.yaml, docs/patterns/machine-learning/multi-node-vllm.md, patterns/multi-node-vllm/Dockerfile, patterns/multi-node-vllm/README.md, patterns/multi-node-vllm/ecr.tf, patterns/multi-node-vllm/eks.tf, patterns/multi-node-vllm/helm.tf, patterns/multi-node-vllm/lws.yaml, patterns/multi-node-vllm/main.tf, patterns/multi-node-vllm/service.yaml
- Add pattern for multi-node inference
- Several convos with users facing challenges trying to support multi-node inference
=> feat: Add pattern for multi-node inference

patterns/multi-node-vllm/README.md
=> docs: Remove kuberay reference from vllm pattern

patterns/aws-neuron-efa/README.md, patterns/aws-neuron-efa/eks.tf, patterns/ml-capacity-block/README.md, patterns/ml-capacity-block/eks.tf, patterns/ml-container-cache/README.md, patterns/ml-container-cache/eks.tf, patterns/multi-node-vllm/README.md, patterns/multi-node-vllm/eks.tf, patterns/nvidia-gpu-efa/README.md, patterns/nvidia-gpu-efa/eks.tf, patterns/targeted-odcr/README.md, patterns/targeted-odcr/eks.tf
- Add node auto repair to ML patterns
- Node auto repair is beneficial on accelerated workloads where GPUs have high failure rates, to mitigate workload disruptions and manual intervention to remediate
=> feat: Add node auto repair to ML patterns

docs/patterns/.pages
=> docs: Update .pages to add Auto Mode section
