aws-ia/terraform-aws-eks-blueprints

- README.md
- modules/aws-eks-teams/README.md
- modules/aws-eks-teams/locals.tf
if `manifests_dir` was not mentioned under teams, it would fail with error that the attribute doesn't exists under the object.
manifests is not mandatory given by user.
- use TF `try` functionality, as if the attribute doesn't exists return empty set.
- Added temp docs for current situation while using `kubernetes_manifest` while discussing with the team alternative options, for now, users can achieve using the manifests by 2 step deployment. First, deploy the cluster without enabling `manifests_dir` , then enable and added `manifests_dir` and TF apply again.
> team manifest optional attribute , cleaner docs

- .pre-commit-config.yaml
- modules/aws-eks-teams/main.tf
- modules/aws-eks-teams/versions.tf
- providers.tf
- versions.tf
Using `kubernetes_manifest` requires the cluster to be up and running and the API endpoint to be accessible, scenario where you first create a cluster with teams will cause the teams manifests to fail first because of it.
- Using `kubectl_manifest` from `kubectl` provider https://registry.terraform.io/providers/gavinbunney/kubectl/latest
> kubectl_manifest for teams manifests

- .github/workflows/e2e-test.yml
new step that will explicitly check the TF apply step outcome, if it was failure it will fail the whole job after TF destroy step, this is to ensure GH workflow will mark jobs as failures, right now it shows jobs that have TF apply has passed because `continue-on-error: true` is applied to the apply step.
This is mainly needed for proper alerting and avoiding false positives.
> test: fail e2e job if tf apply failed

- deploy/2-eks-cluster-with-import-vpc/eks/main.tf
- modules/kubernetes-addons/providers.tf
- E2E Adding depends on compute resources (can be the whole module) before installing any addons
- Disabling (commenting out the code for now) providers from addons module - following https://www.terraform.io/language/modules/develop/providers#legacy-shared-modules-with-provider-configurations instead
> disable k8s addons providers, passing provider instead

- deploy/2-eks-cluster-with-import-vpc/eks/README.md
- modules/kubernetes-addons/prometheus/values.yaml
Removing default configuration for `remoteWrite` and `verticalPodAutoscaler`. If we need the VPA config then we need to create an explicit dependency  between the two addons.
> fix prometheus values.yaml to remove breaking config

- main.tf
- Deploy VPC CNI windows configmap only when needed
- configmap resource should wait until EKS API endoint is ready (depends on)
This is a temp solution as we may move this resource outside the `main.tf` file
> fix: deploy vpc_cni windows configmap if needed

- examples/7-eks-cluster-with-teams/main.tf
- adding missing kubectl provider block, ensuring kubectl is not using local kube config
> test: add kubectl provider team example

- modules/aws-eks-teams/data.tf
- modules/aws-eks-teams/main.tf
- refactor to use TF data `aws_iam_policy_document` instead of jsonencode for platform team
> refactor: platform team aws_iam_policy_document

- .github/PULL_REQUEST_TEMPLATE.md
Updates the PR templates to create a check for a separate PR for the add-ons repo if the PR creates a new add-on and updates an existing one.
We don't want to lag behind on updating the add-ons repo.
> update PR template to check if separate PR for add-ons repo has been created if applicable

- docs/add-ons/keda.md
- docs/add-ons/prometheus.md
- docs/add-ons/vpa.md
- docs/add-ons/yunikorn.md
- modules/kubernetes-addons/yunikorn/locals.tf
Upgrades yunikorn from 0.11.0 to 0.12.2 and removes comments from all k8s addon documentation that says it defaults to the latest version if the version number is not specified. 
Upgrading 
- https://github.com/aws-samples/ssp-eks-add-ons/pull/7
Testing notes:
- created test directory and filled main.tf file with vpc, eks cluster with yunikorn enabled
- `terraform apply -auto-approve` and check that deployment completes
- Connected to cluster and verify that nodes are online
- Accessed the webui and verified page loads:
- `kubectl port-forward svc/yunikorn-service 9889:9889 -n yunikorn`
- connected to http://localhost:9889 without issue
> Upgrade yunikorn version

- examples/karpenter/README.md
- examples/karpenter/main.tf
- examples/karpenter/provisioners/default_provisioner.yaml
- This example shows a pattern on how to deploy multiple Karpenter Cluster Autoscaler Provisioners
- Users feedback on Karpenter to manage provisioners using Terraform
> Karpenter example with default provisioner

- eks-worker.tf
- examples/eks-cluster-with-import-vpc/eks/main.tf
- locals.tf
- modules/aws-eks-teams/README.md
- modules/aws-eks-teams/locals.tf
- modules/aws-eks-teams/outputs.tf
- modules/kubernetes-addons/argo-rollouts/locals.tf
- modules/kubernetes-addons/cluster-autoscaler/locals.tf
- modules/kubernetes-addons/prometheus/locals.tf
- remove `depends_on` of the aws_auth and eks module from the worker which will speed up `terraform plan` times
- add  & adjust helm chart timeouts to reduce time out / context deadline failures 
- terraform plan takes longer than expected, `depends_on` is major functionality (explicit depndency) that increases the time of the TF plan
> Fix/workers and aws-auth depends_on - improve TF plan time

- .github/workflows/e2e-test.yml
- This variant of the `apply` command `implicitly creates a new plan` and then immediately applies it. The -auto-approve option tells Terraform not to require interactive approval of the plan before applying it.
- This will reduce the E2E tests time up to 7 mins.
> Terraform plan removed from e2e test workflow

- modules/kubernetes-addons/aws-opentelemetry-eks/main.tf
>  aws-opentelemetry-eks allow user overrides for addon_config

- examples/observability/eks-cluster-with-amp-amg-opensearch/main.tf
- modules/kubernetes-addons/aws-opentelemetry-eks/main.tf
- Adding `depends_on` for observability example to correct resources flow creation (VPC -> Cluster -> Addons etc.)
- addressing https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues/267 issue(s)
- `aws_iam_service_linked_role` should be deleted only after the opensearch is deleted
- fixing failures around context deadlines and time outs for the example
> fix: adding depndencies observability example

- modules/aws-eks-managed-node-groups/locals.tf
- modules/aws-eks-managed-node-groups/main.tf
- modules/aws-eks-managed-node-groups/managed-launch-templates.tf
- modules/aws-eks-self-managed-node-groups/locals.tf
- modules/aws-eks-self-managed-node-groups/main.tf
- modules/aws-eks-self-managed-node-groups/self-managed-launch-templates.tf
- Fix for Self managed node groups launch templates #270
- Default subnets for node groups to be used in TFVARS #250 
- release version for managed node groups #275 
> Self managed node groups launch template fix

- docs/node-groups.md
- examples/eks-cluster-with-windows-support/README.md
- examples/eks-cluster-with-windows-support/k8s/windows-iis-aspnet.yaml
- examples/eks-cluster-with-windows-support/main.tf
This updates ensures the Windows support example will continue to work regardless of new changes merged into the SSP repo. Also includes code improvements to ensure proper workload node assignment and avoiding EKS cluster creation error in case of reduced capacity in specific AZs, and README, and docs improvements.
As Windows support example is typically not tested by multiple code contributors and approvers, it has got broken multiple times in the past, including the recent changes. This update will pin the version of the SSP module that is known to work, avoid impact of new bugs, and allow sufficient time to upgrade the example for new changes.
> Updated Windows example and docs

- docs/add-ons/keda.md
- docs/add-ons/prometheus.md
- docs/add-ons/vpa.md
- examples/advanced/k8s_addons/main.tf
- examples/analytics/emr-on-eks/examples/EMR-EKS-AMP-AMG-BLOG.md
- examples/analytics/emr-on-eks/main.tf
- examples/analytics/spark-k8s-operator/main.tf
- modules/kubernetes-addons/keda/locals.tf
- modules/kubernetes-addons/vpa/locals.tf
Updates the helm chart for keda to 2.6.2 and updates keda helm chart version references in examples and documentation. 
This also removes some old comments that don't apply - references to default versions and namespaces that are no longer true.
- https://github.com/aws-samples/ssp-eks-add-ons/pull/16
Test notes:
- created test directory and filled main.tf file with vpc, eks cluster with metrics server addon enabled
- ran `terraform apply -auto-approve` and checked that deployment completes
- ran `kubectl logs -n keda-ns <pod>` to check logs for errors for both pods
> Update keda helm chart version

- README.md
- examples/advanced/k8s_addons/main.tf
- examples/advanced/live/preprod/eu-west-1/application_acct/dev/main.tf
- examples/analytics/emr-on-eks/main.tf
- examples/analytics/spark-k8s-operator/main.tf
- examples/ci-cd/gitlab-ci-cd/main.tf
- examples/crossplane/main.tf
- examples/eks-cluster-with-argocd/main.tf
- examples/eks-cluster-with-eks-addons/main.tf
- examples/eks-cluster-with-fargate-profiles/main.tf
- examples/eks-cluster-with-import-vpc/eks/main.tf
- examples/eks-cluster-with-new-vpc/main.tf
- examples/eks-cluster-with-self-managed-node-groups/main.tf
- examples/eks-cluster-with-teams/main.tf
- examples/eks-cluster-with-windows-support/main.tf
- examples/eks-fully-private-eks-cluster/main.tf
- examples/game-tech/agones-game-controller/main.tf
- examples/ingress-controllers/nginx/main.tf
- examples/karpenter/main.tf
- examples/observability/eks-cluster-with-amp-amg-opensearch/main.tf
- variables.tf
Sets `create_eks` to `true` by default and removes unnecessary use of the variable from examples.
Customers will need the control plane in most cases when using the framework. Very few customers are going to leverage an existing control plane. To that end the default behavior should be `create_eks = true` as is documented in our [README](./README.md).
- [N/A] Yes, I have added a new example under [examples](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples) to support my PR
- [N/A] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/ssp-eks-add-ons) repo (if applicable)
> change create eks default

- examples/eks-cluster-with-windows-support/README.md
- modules/kubernetes-addons/argocd/argocd-application/templates/application.yaml
- modules/kubernetes-addons/argocd/main.tf
Removes hardcoded namespace values in the argocd kubernetes addon module. Those entries now reference the argocd helm config.
Addressing: https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues/236
Thanks [sarasensible](https://github.com/sarasensible) for reporting this! 
Testing notes:
- created test directory and filled main.tf file with vpc, eks cluster with argocd addon enabled
- ran `terraform apply -auto-approve` and checked that deployment completes
- verified login page to argocd management console loaded with kubectl port-forwarding: `kubectl port-forward svc/argo-cd-argocd-server -n argocd 8080:443`
- added non-default argocd namespace to kubernetes addon module and …
> Remove hardcoded namespace values in argocd

- docs/node-groups.md
- examples/advanced/live/preprod/eu-west-1/application_acct/dev/main.tf
- modules/aws-eks-fargate-profiles/locals.tf
- modules/aws-eks-managed-node-groups/README.md
- Adds examples for k8_taints in the managed-node-group documentation files.
- Removes k8s_taints from examples that passed them into self-managed node groups as EKS only supports taints through [managed node groups](https://docs.aws.amazon.com/eks/latest/userguide/node-taints-managed-node-groups.html).
- Removes k8_taints local from the aws-eks-fargate-profile module `locals.tf` for the same reason as above, and it wasn't being used.
Addressing a [documentation request](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues/205) for k8s_taints for managed node groups. Thanks for reporting this [schwichti](https://github.com/schwichti)!
> Update k8s_taints documentation and taints fixes

- examples/analytics/emr-on-eks/README.md
- examples/analytics/emr-on-eks/main.tf
Replaced hardcoded value '3'  in main file with local.count_availability_zone to solve deployment issues in regions with less than 3 AZs
Issue : 
While testing   emr-on-eks example on region : US-WEST-1 : 
`Error: Invalid function argument│ │ on main.tf line 77, in module "aws_vpc":│ 77: public_subnets = [for k, v in slice(data.aws_availability_zones.available.names, 0, 3) : cidrsubnet(local.vpc_cidr, 8, k)]│ │ Invalid value for "end_index" parameter: end index must not be greater than the length of the list.╵ `
Tested the code in us-west-1  region and us-east-1  after the fix . Its working fine 
us-west-1  have 2 AZs and us-east-1 have 3 Azs
we limit the AZs to 3 , In case if any region have more …
> Replaced hardcoded value '3' with local.count_availability_zone to solve deployment issues with  regions with less AZss

- modules/kubernetes-addons/cert-manager/README.md
- modules/kubernetes-addons/cert-manager/locals.tf
- modules/kubernetes-addons/cert-manager/main.tf
- modules/kubernetes-addons/cert-manager/variables.tf
- modules/kubernetes-addons/main.tf
* Refactors `cert-manager` add-on to leverage the `helm_addon` submodule. 
* Bumps `cert-manager` version to `v1.7.1`
* Changes `cert-manager` from namespace `kube-system` to `cert-manager` per `cert-manager` docs.
* Removes boilerplate.
Removing unneeded boilerplate code.
- [] Yes, I have added a new example under [examples](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples) to support my PR
- [] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/ssp-eks-add-ons) repo (if applicable)
- [] Yes, I have updated the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/docs) for this feature
> Refactoring cert-manager to leverage helm_addon module

- modules/kubernetes-addons/keda/locals.tf
- modules/kubernetes-addons/keda/variables.tf
The missing IAM role path is causing a plan with this module to fail.
This value is accepted by the IRSA module, so reinstate it and pass to
the module via the IRSA configuration.
PR #312 introduced a breaking change. Remove of the `iam_role_path` prevents `terraform plan` from succeeding. Instead it fails with:
```
│ Error: Reference to undeclared input variable
│ 
│   on .terraform/modules/kubernetes-addons/keda/main.tf line 15, in resource "aws_iam_policy" "keda_irsa":
│   15:   path        = var.iam_role_path
│ 
│ An input variable with the name "iam_role_path" has not been declared. This
│ variable can be declared with a variable "iam_role_path" {} block.
╵
```
This change reintroduces that configuration parameter. It appears that it is supported as a configuration option by the IRSA …
> Fix keda role path

- .github/workflows/e2e-all-tests-parallel.yml
> fix: set fail-fast to false GH matrix

- .github/workflows/e2e-all-tests-parallel.yml
> fix: remove advanced/live example from e2e matrix

- examples/managed-node-groups/main.tf
- fixing managed node group example - bottlerocket ami string was incorrect, needs to be lower case `x`
> fix: fix example - ami type string

- examples/windows-node-groups/README.md
- examples/windows-node-groups/main.tf
- use `us-west-2` as the default region for windows-node-group example to align with other examples and allow run for e2e workflow testing
> fix: windows-node-group to use us-west-2 region

- modules/kubernetes-addons/crossplane/aws-provider/aws-controller-config.yaml
- modules/kubernetes-addons/crossplane/aws-provider/jet-aws-controller-config.yaml
- Adding debug arg to Crossplane 
> Crossplane controller config with debug args

- examples/managed-node-groups-tfvars/README.md
- examples/managed-node-groups-tfvars/data.tf
- examples/managed-node-groups-tfvars/eks.tf
- examples/managed-node-groups-tfvars/main.tf
- examples/managed-node-groups-tfvars/variables.tf
- examples/managed-node-groups-tfvars/variables.tfvars
Adding example showing the usage of variable file as discussed in https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues/332.
It may be another handy example about using the module...
> Add managed-node-groups-tfvars example

- examples/eks-cluster-with-new-vpc/main.tf
- examples/managed-node-groups-tfvars/README.md
- modules/aws-eks-managed-node-groups/README.md
- modules/aws-eks-managed-node-groups/iam.tf
- modules/aws-eks-managed-node-groups/locals.tf
- modules/aws-eks-managed-node-groups/main.tf
- modules/aws-eks-managed-node-groups/managed-launch-templates.tf
- Create TF resource per  IAM role policy attach for known policies
- Add `depends_on` for `eks-cluster-with-new-vpc` example between accelerator module and vpc
- Remove fargate_profiles from the example to allow GovCloud users to try the example.
Cleaner TF destroy, avoid scenarios where VPC resources are deleted before EKS managed node groups does which leads to exceptions and the need of multiple destroy retries.
> Allow usage of depends_on for accelerator module, remove fargate_profiles from base example

- docs/add-ons/yunikorn.md
- examples/analytics/spark-k8s-operator/main.tf
- examples/complete-kubernetes-addons/main.tf
- modules/kubernetes-addons/yunikorn/locals.tf
- Removes `incubator` reference for yunikorn project as they moved out of it 
https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues/368
> fix: remove incubator reference for yunikorn

- modules/kubernetes-addons/aws-vpc-cni/main.tf
> IPv6 VPC CNI Policy hot fix

- docs/add-ons/agones.md
- examples/game-tech/agones-game-controller/README.md
- examples/game-tech/agones-game-controller/main.tf
- Agones example update with correct namespace
- Docs update with latest info
- Agones helm chart version uplift
- Agones Add-on readme update
> Agones example fix with correct namespace

- KNOWN_ISSUES.md
- README.md
- main.tf
- variables.tf
Fixes orphaned cloudwatch logs group that's sometimes left over after destroy.
https://github.com/aws-ia/terraform-ssp-amazon-eks/issues/203
> update terraform-aws-module/eks to v18.17.0 to fix cloudwatch logs issue

- modules/kubernetes-addons/crossplane/README.md
- modules/kubernetes-addons/crossplane/main.tf
- add hard coded 30 sec sleep between crossplane aws provider manifest and aws provider config manifest
- We've seen failures deploying crossplane example due to crossplane provider CRDs not deployed yet while custom APIs manifests trying to be deployed, leading to errors such as:
```
Error: aws-provider-config failed to create kubernetes rest client for update of resource: resource [aws.crossplane.io/v1beta1/ProviderConfig] isn't valid for cluster, check the APIVersion and Kind fields are valid[2350](https://github.com/Zvikan/aws-eks-accelerator-for-terraform/runs/5740005740?check_suite_focus=true#step:10:2350)[2351](https://github.com/Zvikan/aws-eks-accelerator-for-terraform/runs/5740005740?check_suite_focus=true#step:10:2351)  with …
```
> fix: re-add sleep to crossplane aws provider

- README.md
- examples/crossplane/main.tf
- examples/karpenter/README.md
- examples/karpenter/main.tf
- main.tf
- modules/aws-eks-self-managed-node-groups/locals.tf
- variables.tf
- Adds additional sec group rules to nodes and cluster sec groups as per Karpenter 
- Handling AMI as per the  current region
> Karpenter fix for AMI and sec group rules

- modules/kubernetes-addons/main.tf
Signed-off-by: Yaroslav Skopets <yaroslav@tetrate.io>
Bump version of [github.com/tetratelabs/terraform-eksblueprints-tetrate-istio-addon](https://github.com/tetratelabs/terraform-eksblueprints-tetrate-istio-addon).
Update any terraform module references to us [github.com/aws-ia/terraform-aws-eks-blueprints](http://github.com/aws-ia/terraform-aws-eks-blueprints) instead of [github.com/aws-samples/aws-eks-accelerator-for-terraform](http://github.com/aws-samples/aws-eks-accelerator-for-terraform)
Since new AWS repo [github.com/aws-ia/terraform-aws-eks-blueprints](http://github.com/aws-ia/terraform-aws-eks-blueprints) is not visible to me, I couldn't test the change.
> addons: update Tetrate Istio Distribution addon

- .github/workflows/e2e-parallel-destroy.yml
- .github/workflows/e2e-parallel-full.yml
- examples/ingress-controllers/nginx/README.md
- examples/ingress-controllers/nginx/main.tf
- examples/ingress-controllers/nginx/nginx_values.yaml
- examples/ingress-controllers/nginx/values.yaml
- modules/kubernetes-addons/ingress-nginx/values.yaml
- remove default values from nginx addon module
- enable AWS load balancer controller (LBC) in nginx example
- LBC to be deployed before nginx, and to be destroyed after nginx to avoid issues that resources are left behind and nginx can't delete namespace properly - see https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1629
- Adjust example's README 
- nginx example failing right now using default annotations of LBC while LBC not being deployed
- Show correct order of deployments instead of single TF apply/destroy to avoid issues where VPC resources deleted before addons/cluster, and for nginx to be deleted before LBC for this example.
> chore: nginx example to leverage aws load balancer controller

- docs/add-ons/vault.md
- modules/kubernetes-addons/locals.tf
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/variables.tf
Hello maintainers 👋🏼 - adding this as draft while we get the final bits and pieces in places.
---
This PR adds a reference to the HashiCorp Vault blueprint. 
We love EKS and believe we should make it easier to manage and protect secrets (and sensitive data, in general) in an EKS workflow.
> As we are adding an external add-on, our example code lives in the external repository.
> Not applicable.
> Adds support for HashiCorp Vault

- .github/workflows/e2e-parallel-destroy.yml
- .github/workflows/e2e-parallel-full.yml
- modules/kubernetes-addons/README.md
- adds 45 second sleep between TF destroy in e2e parallel workflows
- Adding a delay (sleep) between VPC CNI and deletion of EKS nodes may help reduce the failure rates due to the VPC CNI issues where ENIs are not being cleaned up (TF can't delete subnets/VPC etc.), this should allow ipamd more time to clean up the ENIs
> Add sleep between terraform destroy e2e parallel

- README.md
- docs/add-ons/index.md
- docs/core-concepts.md
- docs/getting-started.md
- docs/index.md
- docs/teams.md
- examples/eks-cluster-with-new-vpc/README.md
- examples/eks-cluster-with-new-vpc/main.tf
- examples/ingress-controllers/nginx/README.md
- examples/ingress-controllers/nginx/main.tf
- modules/kubernetes-addons/README.md
Documentation updates. Readme, getting started guide, and a few other doc pages. 
> Doc updates for README and Getting Started guide

- modules/kubernetes-addons/external-dns/locals.tf
Typo in argocd config for external-dns.
> bug(addon): typo in gitops config for external-dns

- examples/ingress-controllers/nginx/README.md
- examples/ingress-controllers/nginx/main.tf
- re-adds AWS lb controller to the nginx example 
- fix nginx example README to use correct cli command for TF destroy
- 
- part of PR and commit in https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/bdeef58bb58b49ea18ffbba742ad6c8eeabe050f#diff-fcdd8d00f7a7978adb63eea56e712bf41b4ddf153bf7b76d1c68d82e80dcd895L139-L150 was done by a mistake and should be reverted.
> fix: re-add lb controller nginx example

- docs/add-ons/nginx.md
- examples/gitops/argocd/main.tf
- examples/gitops/argocd/variables.tf
- modules/kubernetes-addons/ingress-nginx/locals.tf
PR has two changes to enhance the experience of running the [argocd example](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/gitops/argocd) in govCloud:
- Remove hardcoded region and move it into a variable that can more easily overridden 
- Update the Nginx module to create the `nginx namespace` instead of the `ingress-nginx namespace`. With the old namespace nothing would get created for Nginx beyond an empty namespace and the following error could be seen on Argo cd: 
`Failed sync attempt to c0d70e7b110803dd967c91fec4cba9bd9622bcab: one or more objects failed to apply, reason: namespaces "nginx" not found (retried 1 times).`
Once the correct namespace is created, everything syncs properly and all appropriate resources are created
Testing the ArgoCd example in …
> Fix/ running ArgoCd example on GovCloud

- examples/aws-efs-csi-driver/main.tf
- examples/eks-cluster-with-import-vpc/eks/main.tf
- examples/eks-cluster-with-new-vpc/main.tf
- examples/ingress-controllers/nginx/main.tf
- examples/ipv6-eks-cluster/main.tf
- examples/node-groups/windows-node-groups/main.tf
- Removes `enable_amazon_eks_vpc_cni` from most examples
- Assist with the [known issues](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/KNOWN_ISSUES.md#timeouts-on-destroy) around VPC CNI where ENIs are not being deleted, the default behavior when `enable_amazon_eks_vpc_cni` is that EKS will deploy the VPC CNI but customer may not be able to customize it, for most of the default examples this is not required, however if users would like to customize they can follow the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/add-ons/managed-add-ons.md).
- When VPC CNI is deployed by default, this allows a smoother experience when TF destroy executed by the user in the correct order, example:
```
terraform destroy …
```
> Remove enable_amazon_eks_vpc_cni from examples

- test/go.mod
- test/go.sum
- Issue reported by the Dependabot for go versions 
- Bumped to latest version for Hashicorp go-getter used in Terratest
> hashicorp go-getter version bump for security fix

- README.md
- data.tf
- variables.tf
- timeout of eks readiness as TF variable instead of hard coded. 
- increase default timeout to 10 minutes instead of 5 minutes. 
- Closes #449
> fix: data eks readiness variable, increase timeout

- examples/ipv6-eks-cluster/README.md
- examples/ipv6-eks-cluster/main.tf
- setting `enable_amazon_eks_vpc_cni` to true 
- fixing cluster name value in README
- example is failing to deploy without having `enable_amazon_eks_vpc_cni` set to true as it needs to be set for `enable_ipv6` variable.
- README had incorrect cluster name for the AWS CLI command.
> fix: enable vpc cni for ipv6 example

- docs/add-ons/managed-add-ons.md
- examples/eks-cluster-with-new-vpc/main.tf
- modules/kubernetes-addons/aws-coredns/locals.tf
- modules/kubernetes-addons/aws-coredns/main.tf
- modules/kubernetes-addons/aws-kube-proxy/locals.tf
- modules/kubernetes-addons/aws-kube-proxy/main.tf
- modules/kubernetes-addons/aws-vpc-cni/locals.tf
- modules/kubernetes-addons/aws-vpc-cni/main.tf
- outputs.tf
- Currently EKS Add-ons are controlled by the `kubernetes-addon`  sub module. VPC CNI add-on is getting deleted when we destroy kubernetes-addon before the cluster and node groups. 
- This feature will cleanup the EKS managed add-ons as and preserve the add-on as self-managed addon. This will ensure cirtical add-ons are running even after the add-ons and node groups are deleted
- Preserved self-managed addons will be deleted automatically when you delete the cluster
- This is added only for critical addons vpc-cni, coredns and kube-proxy. We will revise if its required for other managed add-ons
- If this users wanted to delete the add-on completely then can always pass `preserve=false`
- #510 - fixes the description issue
**Note**: Not all the PRs required examples and docs except a new …
> Add preserve for EKS Managed Addons

- README.md
- docs/add-ons/managed-add-ons.md
- modules/kubernetes-addons/aws-cloudwatch-metrics/locals.tf
Replaces a hardcoded `aws` partition in the cloudwatch agent addon policy arn in the aws-cloudwatch-metrics addon with a dynamic partition so it's compatible with GovCloud. Without this, any deployments using the `aws-cloudwatch-metrics` addon in GovCloud will fail.
Tested by applying and destroying `examples/eks-cluster-with-new-vpc` in GovCloud.
> Add dynamic partition to aws-cloudwatch-metrics cloudwatch agent addon policy arn

- .github/workflows/plan-examples.yml
- Fix repository check to avoid failed plans on contributor forks
- External contributors do not have access to the secrets used to run plans, which results in a number of failed checks that are not actionable for them. I thought the previous check for forks solved this but it does not appear to be working as intended - using solution posted here https://github.com/actions/runner/issues/859
> ci: Fix repository check to avoid failed plans on contributor forks

- main.tf
- modules/aws-eks-teams/README.md
- modules/aws-eks-teams/main.tf
- modules/aws-eks-teams/variables.tf
This fixes bug #532 , and makes the teams module honor the permissions boundary in the main blueprints module. 
We hit this bug testing blueprints, and thought it was a pretty straightforward fix. 
- Closes #532 
- [ x ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
> [bugfix]: #532: Have teams module honor permissions boundary

- modules/kubernetes-addons/karpenter/data.tf
Based on a similar issue to https://github.com/aws/karpenter/issues/1706
This policy lacks `"ec2:DeleteLaunchTemplate",` and this ends up with:
`2022-05-12T18:03:24.151Z	ERROR	controller.aws.launchtemplate	Unable to delete launch template, UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message:`
add `      "ec2:DeleteLaunchTemplate*",`
Fixes `Unable to delete launch template,` error
> adds DeleteLaunchTemplate to karpenter policy

- examples/karpenter/main.tf
- examples/karpenter/provisioners/default_provisioner.yaml
- examples/karpenter/provisioners/default_provisioner_with_launch_templates.yaml
This PR fixes subnetSelector in karpenter provisioner by using VPC name e.g. `${eks-vpc_name}-private*` => `aws001-preprod-dev-vpc-private*`
If we already have a non-default VPC in account then `*private*` subnet selecter will select private subnets from all available VPCs as shown in this image.
Karpenter will then discover all private subnets (from all VPCs) and will try to launch nodes in a different VPC and we will get this error.
Error log:
```
2022-05-14T12:58:21.515Z	ERROR	controller.provisioning	Could not launch node, launching instances, with fleet error(s), InvalidParameter: Security group sg-08772d703d36e84ab and subnet subnet-06ab25f078c0630e5 belong to different networks.; InvalidParameter: Security group sg-08772d703d36e84ab and subnet subnet-04adc26d50a7c8249 belong to …
```
> [examples/karpenter] karpenter provisioner: use eks-vpc_name in subnetSelector to prevent subnet conflicts with other VPCs

- .github/workflows/stale_issue_pr.yaml
- add stale workflow for Issues and PRs
- healthy practice as project keeps growing and we need to keep track of things.
- inspired by https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/.github/workflows/stale-actions.yaml and https://github.com/aws/amazon-vpc-cni-k8s/blob/master/.github/workflows/stale_issue_pr.yaml configs
> Add stale workflow

- .github/workflows/e2e-parallel-destroy.yml
- .github/workflows/e2e-parallel-full.yml
- .github/workflows/plan-examples.yml
- Adds concurrency to E2Es workflows (parallel apply & destroy)
- Sets TF plan to use pull_request_target and use GitHub environment.
- concurrency to prevent from multiple TF apply/destroy run on the same time as the state is the same - https://docs.github.com/en/actions/using-jobs/using-concurrency
- Allows PRs from forks to run against TF plan checks by allowing `pull_request_target` to be used while utilizing [GitHub Environment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) to prevent ["pwn request"](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/), allowing humans (repo code owners) to review the PRs and deploy relevant checks when it's safe to do so.
**Note**: Not all the PRs …
> Allow TF plan checks to run on forks PRs, add concurrency to parallel E2Es 

- .github/workflows/e2e-terratest.yml
- Adding Github Workflow Concurrency to e2e-terratest. Checkout this link for more details https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/#:~:text=GitHub%20Actions%20now%20supports%20a,running%20at%20any%20given%20time.
- 
> Adding github workflow concurrency to terratest

- examples/analytics/emr-on-eks/main.tf
- examples/analytics/spark-k8s-operator/main.tf
- examples/aws-efs-csi-driver/main.tf
- examples/complete-kubernetes-addons/main.tf
- examples/crossplane/main.tf
- examples/eks-cluster-with-external-dns/main.tf
- examples/eks-cluster-with-new-vpc/main.tf
- examples/fargate-serverless/main.tf
- examples/fully-private-eks-cluster/main.tf
- examples/game-tech/agones-game-controller/main.tf
- examples/gitops/argocd/main.tf
- examples/ingress-controllers/nginx/main.tf
- examples/ipv6-eks-cluster/main.tf
- examples/karpenter/main.tf
- examples/node-groups/managed-node-groups/main.tf
- examples/node-groups/windows-node-groups/main.tf
- examples/observability/adot-amp-grafana-for-haproxy/main.tf
- examples/observability/adot-amp-grafana-for-java/main.tf
- examples/observability/adot-amp-grafana-for-memcached/main.tf
- examples/observability/adot-amp-grafana-for-nginx/main.tf
- examples/observability/amp-amg-opensearch/main.tf
- examples/tls-with-aws-pca-issuer/main.tf
- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/data.tf
- modules/kubernetes-addons/locals.tf
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/variables.tf
- Passing EKS Blueprint outputs to addons module as inputs (vars) instead of using eks data resource in k8s-addons module 
- Support updates without disruptive changes (depends_on forcing downstream modules/resources to re-compute) - e.g. may occur during cluster upgrade process
- Building a better implicit dependency map (goes towards the single apply, ensuring correct ordering)
TODO: 
- Parallel E2E tests needs to be done on this PR, plan examples [passed successfully](https://github.com/aws-ia/terraform-aws-eks-blueprints/actions/runs/2418089266)
> [Kubernetes Addons Module] - Use EKS outputs instead of data resources

- test/go.mod
- test/go.sum
- Security go package fix for hashicorp go-getter
> Go package security update for hashicorp go-getter

- modules/kubernetes-addons/aws-load-balancer-controller/data.tf
- modules/kubernetes-addons/kubernetes-dashboard/main.tf
Adds missing permission to IAM role assume by AWS Load Balancer Controller pods.
While deploying example at "examples/ipv6-eks-cluster" an EKS cluster along with addon alb-ingress-controller is created. However when I tried to create an Ingress, alb-ingress-controller pod was failing to add targets to TargetGroup with AccessDenied error on permission "ec2:DescribeVpcPeeringConnections". Thus this PR includes commit on missing permission "ec2:DescribeVpcPeeringConnections".
> updated IAM policy for lb2 service account

- examples/analytics/emr-on-eks/README.md
- examples/analytics/spark-k8s-operator/README.md
- examples/aws-efs-csi-driver/README.md
- examples/complete-kubernetes-addons/README.md
- examples/crossplane/README.md
- examples/eks-cluster-with-external-dns/README.md
- examples/eks-cluster-with-new-vpc/README.md
- examples/game-tech/agones-game-controller/README.md
- examples/ipv6-eks-cluster/README.md
- examples/karpenter/README.md
- examples/node-groups/managed-node-groups/README.md
- examples/node-groups/windows-node-groups/README.md
- examples/tls-with-aws-pca-issuer/README.md
- Correct target destroy resource name for VPC
- Resource name is `module "vpc" {}`
- Relates to #601 and #602 (will need to push new release for doc update)
> fix: Correct target destroy resource name for VPC

- docs/extensibility.md
- mkdocs.yml
Fixes the link to edit pages.
Today, clicking on the pen to suggest a pull request leads to a 404 error. This is because the code is on main branch where mkdocs expects master by default. See [mkdocs documentation](https://www.mkdocs.org/user-guide/configuration/).
None
> docs: fix link (pen) to edit pages

- examples/observability/adot-amp-grafana-for-haproxy/main.tf
- examples/observability/adot-amp-grafana-for-haproxy/variables.tf
- examples/observability/adot-amp-grafana-for-java/main.tf
- examples/observability/adot-amp-grafana-for-java/variables.tf
- examples/observability/adot-amp-grafana-for-memcached/main.tf
- examples/observability/adot-amp-grafana-for-memcached/variables.tf
- examples/observability/adot-amp-grafana-for-nginx/main.tf
- examples/observability/adot-amp-grafana-for-nginx/variables.tf
AWS regions settings were hardcoded in some samples, confusing some users
> Remove hardcoded regions

- docs/index.md
Finally adding the official workshop link.
> docs: adding workshop link

- examples/eks-cluster-with-new-vpc/README.md
- examples/eks-cluster-with-new-vpc/main.tf
- Correct docs on resources created in example
- Closes #608 
> fix: Correct docs on resources created in example

- aws-auth-configmap.tf
- modules/emr-on-eks/main.tf
- modules/irsa/main.tf
- modules/kubernetes-addons/adot-collector-haproxy/main.tf
- modules/kubernetes-addons/adot-collector-java/main.tf
- modules/kubernetes-addons/adot-collector-memcached/main.tf
- modules/kubernetes-addons/adot-collector-nginx/main.tf
- modules/kubernetes-addons/agones/main.tf
- modules/kubernetes-addons/argo-rollouts/main.tf
- modules/kubernetes-addons/argocd/main.tf
- modules/kubernetes-addons/crossplane/main.tf
- modules/kubernetes-addons/fargate-fluentbit/main.tf
- modules/kubernetes-addons/ingress-nginx/main.tf
- modules/kubernetes-addons/metrics-server/main.tf
- modules/kubernetes-addons/opentelemetry-operator/main.tf
- modules/kubernetes-addons/prometheus/main.tf
- modules/kubernetes-addons/spark-k8s-operator/main.tf
- modules/kubernetes-addons/traefik/main.tf
- modules/kubernetes-addons/vpa/main.tf
- modules/kubernetes-addons/yunikorn/main.tf
- Removes the `app.kubernetes.io/managed-by` label from Terraform created resources
- Avoid competing updates with Helm
- Fixes #499 
> fix: Remove `app.kubernetes.io/managed-by` label

- examples/eks-cluster-with-external-dns/main.tf
- examples/karpenter/main.tf
- examples/observability/amp-amg-opensearch/main.tf
- Remove remaining `depends_on` from addon definitions in examples to avoid upgrade disruptions
- Closes #559 (in conjunction with the other PRs attached to that issue, this just removes the last few `depends_on` blocks)
> fix: Remove remaining `depends_on` from examples to avoid upgrade disruptions

- modules/kubernetes-addons/adot-collector-haproxy/locals.tf
- modules/kubernetes-addons/adot-collector-java/locals.tf
- modules/kubernetes-addons/adot-collector-memcached/locals.tf
- modules/kubernetes-addons/adot-collector-nginx/locals.tf
- modules/kubernetes-addons/cert-manager/data.tf
- Replace hardcoded IAM policy ARN partitions with data source partition for non-commercial regions=
- Relates to #582 - this PR removes the remaining hardcoded partition values, but the issue in #582 is actually due to using an older version of blueprints that doesn't contain the fixes
> fix: Replace hardcoded IAM policy ARN partitions with data source partition for non-commercial regions

- examples/karpenter/main.tf
- modules/kubernetes-addons/aws-node-termination-handler/locals.tf
- modules/kubernetes-addons/aws-node-termination-handler/values.yaml
- modules/kubernetes-addons/main.tf
Add node termination handler support for karpenter based on the blog post from aws:
[Using Amazon EC2 Spot Instances with Karpenter]([https://aws.amazon.com/blogs/containers/using-amazon-ec2-spot-instances-with-karpenter/)
Need for node termination support for karpenter
- [] E2E Test successfully complete before merge?
```
--- PASS: TestEksBlueprintsE2E (0.00s)
--- PASS: TestEksBlueprintsE2E/TF_PLAN_VALIDATION (23.13s)
--- PASS: TestEksBlueprintsE2E/TF_OUTPUTS_VALIDATION (7.94s)
--- PASS: TestEksBlueprintsE2E/TF_OUTPUTS_VALIDATION/vpc_cidr (1.62s)
--- PASS: TestEksBlueprintsE2E/TF_OUTPUTS_VALIDATION/vpc_private_subnet_cidr (1.57s)
--- PASS: …
```
> Node termination handler updates for karpenter

- docs/add-ons/velero.md
Fix the link for Velero on the add-ons documentation's section.
> docs: Fix link for Velero add-on on navbar

- modules/aws-eks-managed-node-groups/main.tf
- Re-add labels for managed node groups
- Re-adds labels that were inadvertently removed in https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/484/files#diff-a7a8838394fad05655d13cefd255e1add3a2eab122c3092163c8271bd7d3fda9L65 
- Closes #652
> fix: Re-add labels for managed node groups

- modules/aws-eks-teams/README.md
- modules/aws-eks-teams/outputs.tf
When I create policy and attach it to role,
We need role name like below.
```
resource "aws_iam_role_policy_attachment" "test-attach" {
role       = aws_iam_role.role.name
policy_arn = aws_iam_policy.policy.arn
}
```
> [teams module] add team_sa_irsa_iam_role to output

- .github/workflows/e2e-parallel-full.yml
- Adjust e2e parallel to  use multiple TF apply in order by modules (vpc->blueprints->addons) using -target
- While working on https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/634 and running the e2e parallel multiple times, we [identified failures](https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/634#issuecomment-1158489670) where addons are timing out as the addons were created in parallel when worker nodes were created, and worker nodes might take up to 10 minutes (or more) to be properly created, leading to helm/addons timeouts error messages.
Targeting and deploying modules in order should prevent from this issue to happen as addons will not be created in parallel with the workers nodes, but only after worker nodes have been deployed successfully.
To keep things …
> fix: e2e multiple TF apply in order using "-target"

- test/src/eks_blueprints_e2e_test.go
- Setting expected worker nodes to 2 in terratest.
- Terratest currently failing because of that.
[Example](https://github.com/aws-ia/terraform-aws-eks-blueprints/runs/6989483103?check_suite_focus=true) 
```
=== RUN   TestEksBlueprintsE2E/EKS_ADDON_VALIDATION/MATCH_TOTAL_EKS_WORKER_NODES
eks_blueprints_e2e_test.go:253: 
Error Trace:	eks_blueprints_e2e_test.go:253
Error:      	Not equal: 
expected: 3
actual  : 2
Test:       	TestEksBlueprintsE2E/EKS_ADDON_VALIDATION/MATCH_TOTAL_EKS_WORKER_NODES
```
> fix: terratest expected worker nodes to 2

- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/main.tf
This PR upgrades the Ondat addon to the latest release, [0.1.0](https://github.com/ondat/terraform-eksblueprints-ondat-addon/releases). This installs `v2.7.0` of Ondat, now with etcd in-cluster using GP3 volumes for backing store in the default blueprint with additional ephemeral storage and external etcd examples.
New features for Ondat addon.
N/A
> Update Ondat addon version

- modules/kubernetes-addons/karpenter/data.tf
Signed-off-by: Fernando Miguel <github@FernandoMiguel.net>
adds two extra IAM permissions to karpenter
Two new IAM permissions will be required on the next karpenter release
https://github.com/aws/karpenter/pull/1994/files
https://github.com/aws/karpenter/pull/1994/files
> feat: Update karpenter permissions for making more accurate decisions regarding spot deployments

- .github/workflows/plan-examples.py
Skips the full-private-eks-cluster example. This is a temporary change which will be reverted once the example is refactored.
> Update plan-examples.py to skip full-private

- examples/upstream-with-k8s-addons/main.tf
- Enabling control plane logs for upstream example
- tfsec check failing due to control plane logs not enabled - https://github.com/aws-ia/terraform-aws-eks-blueprints/runs/7099360400?check_suite_focus=true
> fix: enable cluster log types upstream example

- .github/workflows/e2e-parallel-destroy.yml
- .github/workflows/e2e-parallel-full.yml
- .github/workflows/plan-examples.py
Last commit for this did not do this properly as the scripts globs the directory.
> Skip fully-private-eks example tests

- docs/node-groups.md
- modules/aws-eks-managed-node-groups/locals.tf
- modules/aws-eks-managed-node-groups/managed-launch-templates.tf
add "launch_template_ignore_changes" option
If I add a tag to `additional_tags`, it will be added to all of them, but there was a situation where I wanted to add an arbitrary tag only to the specifications_tags of launch_template_tag, and I want to make it supported.
eg.
```
locals {
shared_tags = {
Terraform   = "true"
Service       = "Original_Food_Shop"
}
}
provider "aws" {
region = var.aws_region
default_tags {
tags = local.shared_tags
}
}
...
managed_node_groups = {
mg_m5 = {
node_group_name      = "managed-ondemand"
instance_types       = ["m5.large"]
subnet_ids           = module.vpc.private_subnets
min_size             = 2
launch_template_tags = local.shared_tags
}
}
...
```
> feat: Add launch_template_tags variable for additional launch template tags

- modules/kubernetes-addons/cluster-autoscaler/main.tf
- modules/kubernetes-addons/cluster-autoscaler/values.yaml
Previously `image.tag` was set through `set_values`
Due to this we were unable to upgrade cluster-autoscaler
* redifine cluster-autoscaler image.tag on `values.yaml`
* remove `set_values`
Define default value for `cluster-autoscaler` based on cluster version and let user override this value
Resolv #714 
> feat(cluster-autoscaler): allow user to upgrade cluster-autoscaler

- docs/add-ons/external-secrets.md
- examples/external-secrets-kubernetes-addon/README.md
- examples/external-secrets-kubernetes-addon/main.tf
- examples/external-secrets-kubernetes-addon/outputs.tf
- examples/external-secrets-kubernetes-addon/versions.tf
- examples/fully-private-eks-cluster/eks/main.tf
- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/external-secrets/README.md
- modules/kubernetes-addons/external-secrets/locals.tf
- modules/kubernetes-addons/external-secrets/main.tf
- modules/kubernetes-addons/external-secrets/outputs.tf
- modules/kubernetes-addons/external-secrets/variables.tf
- modules/kubernetes-addons/external-secrets/versions.tf
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/variables.tf
Adds the [External Secrets operator](https://external-secrets.io/v0.5.6/) as an addon
The External Secrets operator integrates external secrets management services with a Kubernetes cluster. It's more flexible than the Secret Store CSI driver. It transparently handles secret rotation, as secrets are kept synchronised. By using Kubernetes secrets, it's easy to map secrets as environment variables. 
> External secrets operator

- modules/kubernetes-addons/aws-load-balancer-controller/data.tf
- Add  ELB listener tagging policy
- Update iam:CreateServiceLinkedRole policy to match the recommended policy found [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json).
- Closes #717 
> Add ELB listener tagging policy

- docs/add-ons/argocd.md
- modules/kubernetes-addons/argocd/main.tf
Added the optional insecure parameter for argocd apps. If you do not set the insecure parameter it will set to false by default. This does not break existing configurations.
When using private repositories in private networks you often do not want to manage the public server certificates in addition to the private ones. The risk is very low that a man-in-the-middle attack is performed. Therefore I added the `insecure` parameter which can be set when creating an Argo app.
Argo Docs on the insecure flag: https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#self-signed-untrusted-tls-certificates
This parameter resolves repo server errors like `error testing repository connectivity: ssh: handshake failed`.
- ~~[ ] Yes, I have added a new example under …
> feat(argocd): add insecure parameter for argocd apps

- .github/workflows/markdown-link-check.yml
- docs/add-ons/external-secrets.md
- fix broken link in docs.
- adjust markdown link action to run on PRs against main only when .md files modified.
- broken main check - https://github.com/aws-ia/terraform-aws-eks-blueprints/runs/7149823004?check_suite_focus=true
- it make sense to check this on PR before changes to main (unless I am missing something here).
> fix: markdown links, check markdowns on PR

- modules/kubernetes-addons/aws-efs-csi-driver/data.tf
Add missing ec2:DescribeAvailabilityZones and elasticfilesystem:DescribeMountTargets iam permissions.
ec2:DescribeAvailabilityZones and elasticfilesystem:DescribeMountTargets are needed according to [this](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/489#issuecomment-912585225).
> Add missing permissions needed for EFS CSI

- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/main.tf
Upgrades the Ondat addon for version v2.8
This is a standard part of the upgrade process
N/A
> Upgrade Ondat addon

- .github/workflows/e2e-parallel-full.yml
- fixing indentation on e2e parallel file
- https://github.com/aws-ia/terraform-aws-eks-blueprints/actions/runs/2630872943
> fix: correct gh action indentation

- docs/add-ons/grafana.md
- examples/analytics/spark-k8s-operator/main.tf
- examples/analytics/spark-k8s-operator/versions.tf
- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/grafana/README.md
- modules/kubernetes-addons/grafana/data.tf
- modules/kubernetes-addons/grafana/locals.tf
- modules/kubernetes-addons/grafana/main.tf
- modules/kubernetes-addons/grafana/values.yaml
- modules/kubernetes-addons/grafana/variables.tf
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/variables.tf
- Allows users to pass their secret to grafana adminPassword field through set_sensitive values
- Example added to create a new secret with Secrets Manager and pass that to Helm Chart
> Allows users to pass thier own secrets to Grafana admin

- modules/kubernetes-addons/aws-node-termination-handler/locals.tf
- Adjust NTH event rules names to be unique using cluster id and ensuring string is limited to 64 chars per [docs](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Rule.html) 
- https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/708
- https://github.com/aws-ia/terraform-aws-eks-blueprints/runs/7237688237?check_suite_focus=true
> fix: unique NTH event rules names per cluster id

- examples/gitops/argocd/main.tf
- examples/gitops/argocd/versions.tf
- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/argocd/README.md
- modules/kubernetes-addons/argocd/data.tf
- modules/kubernetes-addons/argocd/locals.tf
- modules/kubernetes-addons/argocd/main.tf
- modules/kubernetes-addons/argocd/variables.tf
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/variables.tf
- Allowing users to pass ArgoCD Admin password using set_sensitive values
-  Example to show how to create a Secrets Manager password and use it for ArgoCD 
Fixes #728 
> ArgoCD admin password update

- examples/analytics/spark-k8s-operator/main.tf
- Fix for the following issue reported by Github Workflow
```
Error: Error uploading object to S3 bucket (spark-***20220711150809370300000001): NotImplemented: A header you provided implies functionality that is not implemented
status code: 501, request id: RQPWNJMCVN624FBY, host id: vEsVLKBT21sGzQ828UnD1wBgc2VwNzhafLY5Ae7X2ilkcPyeXemTa8XAyrtUu3xjSQvDz8Bpclo=
with aws_s3_object.this,
on main.tf line 327, in resource "aws_s3_object" "this":
327: resource "aws_s3_object" "this" {
```
> aws s3 object fix for NotImplemented error

- .github/workflows/e2e-parallel-full.yml
- Changes Iamlive to run in CSM mode instead of Proxy
- Some actions may [fail](https://github.com/iann0036/iamlive/issues/54) in proxy mode, as of now we set wildcard for resource with a big warning, and it is possible to run terraform with CSM with this change.
> fix: iamlive in csm mode

- examples/observability/adot-amp-grafana-for-haproxy/README.md
- examples/observability/adot-amp-grafana-for-haproxy/main.tf
- examples/observability/adot-amp-grafana-for-haproxy/variables.tf
- examples/observability/adot-amp-grafana-for-java/README.md
- examples/observability/adot-amp-grafana-for-java/main.tf
- examples/observability/adot-amp-grafana-for-java/variables.tf
- examples/observability/adot-amp-grafana-for-memcached/README.md
- examples/observability/adot-amp-grafana-for-memcached/main.tf
- examples/observability/adot-amp-grafana-for-memcached/variables.tf
- examples/observability/adot-amp-grafana-for-nginx/README.md
- examples/observability/adot-amp-grafana-for-nginx/main.tf
- examples/observability/adot-amp-grafana-for-nginx/variables.tf
We have provided support for using an existing workspace in the other [observability examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/observability/adot-amp-grafana-for-java/variables.tf#L1-L5). This PR adds the missing support for that in the haxproxy example 
- [x ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
> Support exiting Grafana workspace

- .pre-commit-config.yaml
- UPGRADE-5.0.md
- Add upgrade guide to capture changes and documentation for v5.0 changes
- Provides empty template to populate with changes while v5.0 tasks are completed. Each PR for v5.0 should also include its necessary upgrade documentation which is captured in this document
> chore: Add upgrade guide to capture changes and documentation for v5.0 changes

- docs/add-ons/managed-add-ons.md
- modules/kubernetes-addons/argocd/locals.tf
amazon_eks_vpc_cni_config addon_version v1.10.1-eksbuild.1 -> v1.11.2-eksbuild.1
addon_version v1.11.2-eksbuild.1 is better then v1.10.1-eksbuild.1
> chore: amazon_eks_vpc_cni_config addon_version v1.10.1-eksbuild.1 -> v1.11.2-eksbuild.1, argocd 4.9.1 -> 4.9.14

- test/go.mod
- test/go.sum
- Update terratest dependency to patch reported vulnerability
- Dependabot reported alert
> fix: Update terratest dependency to patch reported vulnerability

- .github/workflows/e2e-parallel-destroy.yml
- .github/workflows/e2e-parallel-full.yml
- README.md
- examples/vpc-cni-custom-networking/README.md
- examples/vpc-cni-custom-networking/main.tf
- examples/vpc-cni-custom-networking/outputs.tf
- examples/vpc-cni-custom-networking/versions.tf
- main.tf
- variables.tf
- Adds an example demonstrating how to enable [AWS VPC-CNI custom networking](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html)
- Updates `terraform-aws-eks` module to v18.26.3 which is latest - update is to allow use of dedicated control plane subnets which are recommended for expanding data plane without cluster disruption
- Closes #474
> feat: Add example for VPC-CNI custom networking

- README.md
- main.tf
- Update EKS module version to restrict TLS provider version
- More info can be found here https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2174 - the tl;dr is that a new v4.0 of the TLS provider was released yesterday and introduced a bug which is causing the `tls_cert` resource to fail. The change in v18.26.6 is just to restrict the provider from using v4.0 which is causing issues
- Closes #795 
> fix: Update EKS module version to restrict TLS provider version

- modules/irsa/main.tf
- Correct IRSA module name used to not default to `null` through `coalesce()`
- Because of the use of optional variable attributes, when a value is not provided it defaults to `null` which is a valid value inside a `try()` block and for IAM role names. When the value is `null`, Terraform will provide a value for it which is not the desired default behavior. Instead, we want to use a custom name if provided, otherwise fall back to the format provided by the module
- Closes #788 
> fix: Correct IRSA module name used to not default to `null` through `coalesce()`

- docs/add-ons/aws-for-fluent-bit.md
- examples/complete-kubernetes-addons/main.tf
- Using correct variable to set the fluentbit cw log group retention in docs and example. 
- Closes https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/786
> fix: fluentbit use correct cw retention variable

- modules/kubernetes-addons/external-dns/data.tf
current policy occurs error in external-dns when user has hosted zone more than 2.
and refer to official document (https://kubernetes-sigs.github.io/external-dns/v0.12.1/tutorials/aws/#iam-policy) , follow the policy guide.
before fix
```
time="2022-07-26T07:44:34Z" level=error msg="failed to list resource records sets for zone /hostedzone/Z0098938DV62NKCC892B: AccessDenied: User: arn:aws:sts::88425xxxxxxx:assumed-role/eks-external-dns-sa-irsa/1658820563382445612 is not authorized to perform: route53:ListResourceRecordSets on resource: arn:aws:route53:::hostedzone/Z0098938DV62xxxxxxxx because no identity-based policy allows the route53:ListResourceRecordSets action\n\tstatus code: 403, request id: cdb13f18-51ba-490b-a0fe-8c21"
```
after apply fix
```
time="2022-07-26T07:46:36Z" level=info …
```
> [addon/external-dns] update irsa policy

- .github/workflows/e2e-terratest.yml
- .github/workflows/plan-examples.yml
- .github/workflows/pre-commit.yaml
- Only run CI checks when necessary (affected files changed)
- Reduce the amount of checks that get executed that are not necessary for the given changeset
> chore: Only run CI checks when necessary (affected files changed)

- docs/add-ons/external-dns.md
- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/external-dns/README.md
- modules/kubernetes-addons/external-dns/data.tf
- modules/kubernetes-addons/external-dns/locals.tf
- modules/kubernetes-addons/external-dns/outputs.tf
- modules/kubernetes-addons/external-dns/values.yaml
- modules/kubernetes-addons/external-dns/variables.tf
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/variables.tf
- Allow users to specify multiple Route53 zones as well as cross account zones with `external-dns`
- Allow setting `set_values` through `helm_config` variable
- Update default `external-dns` helm chart version to latest
- This allows users to use `external-dns` addon with one or more Route53 zones in the current account, external account(s), or both while not requiring them to re-provide the values set in the default `values.yaml` file provided in the addon
- Closes #512 
- Closes #516
- Closes #541
- Closes #638 
> feat: Allow users to specify multiple Route53 zones as well as cross account zones with `external-dns`

- modules/irsa/main.tf
- Fixing a breaking change for IRSA module
- Closes https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/837
> hotfix for oidc issue url for irsa module

- examples/eks-cluster-with-new-vpc/main.tf
- examples/fully-private-eks-cluster/README.md
- modules/kubernetes-addons/cert-manager/locals.tf
- modules/kubernetes-addons/cert-manager/values.yaml
- Enable additional values through `set_values` for `cert-manager`
- Update `cert-manger` helm chart to latest version
- Remove default `securityContext` and use what the default provided by the helm chart https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L117
- Closes #813
- This change allows for additional values to be set on `cert-manager` without needing to re-provide the default values in `values.yaml`. In addition, I have discovered that you can override the values in the `values.yaml` through `set_values`. So in the `eks-cluster-with-new-vpc`, you can see that `--enable-certificate-owner-ref=false` but in the `cert-manager` addon the default values.yaml file has `--enable-certificate-owner-ref=true`. When deployed, the value is as set …
> feat: Enable additional values through `set_values` for `cert-manager`

- modules/aws-eks-self-managed-node-groups/locals.tf
- modules/aws-eks-self-managed-node-groups/main.tf
Pass target_group_arns to self managed nodes autoscaling group
See issue: https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/854
When adding an alb for our nodes there was no way of passing down the target_group_arn to the nodes
This can be circumvented by using an autoscaling attachment but in every other apply the eks_blueprint notices an attachment that isn't defined in the blueprint so it removes it.
See issue: https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/854
> Pass target_group_arns to self managed nodes autoscaling group

- examples/eks-cluster-with-external-dns/main.tf
Fixed the URL for ArgoCD Workload application. It was referring to a wrong URL that was getting 404 error
https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/861
- [-] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [-] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [-] Yes, I have updated …
> Fix for ArgoCD Workload Application URL

- .github/ISSUE_TEMPLATE/bug_report.md
- FAQ.md
- examples/analytics/airflow-on-eks/main.tf
- examples/analytics/emr-eks-fsx-lustre/main.tf
- examples/analytics/emr-on-eks/main.tf
- examples/gitops/argocd/main.tf
- examples/observability/amp-amg-opensearch/main.tf
- Closes #903 
- It's mandatory to install EBS CSI driver for all the add-on which uses GP2 storage class by default. Examples have been updated with EBS CSI driver
- Added instructions to FAQ.doc
- Airflow RDS database was using random password and its now fixed with the actual secrets manager password
- Spell checks on PR template
> EBS CSI driver fix for eks v1.23 and RDS pwd fix for airflow

- docs/add-ons/kubecost.md
- modules/kubernetes-addons/kubecost/locals.tf
This PR fix the repo url for kubecost helm add-on
Closes #913
> fix: Correct kubecost repo URL

- modules/kubernetes-addons/aws-fsx-csi-driver/data.tf
Adding "fsx:UpdateFileSystem" action in the policy, in order to allow dynamic resize of the File System. Without this updated policy, a resize request in PVC results in an error. With this policy, insted, volume resizing works.
Closes #911
Adding "fsx:UpdateFileSystem" action in the policy, in order to allow dynamic resize of the File System. Without this updated policy, a resize request in PVC results in an error. With this policy, insted, volume resizing works.
Volume resizing is required for me, but it can be required for many other users
> fix: Add `fsx:UpdateFileSystem` permission to `aws-fsx-csi-driver` addon

- examples/crossplane/main.tf
- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/reloader/README.md
- modules/kubernetes-addons/reloader/locals.tf
- modules/kubernetes-addons/reloader/main.tf
- modules/kubernetes-addons/reloader/outputs.tf
- modules/kubernetes-addons/reloader/variables.tf
- modules/kubernetes-addons/reloader/versions.tf
- modules/kubernetes-addons/variables.tf
Adds [Reloader](https://github.com/stakater/Reloader) to the Kubernetes addons deployable. 
My company intends to use this addon in our deployment. Adding it to the blueprints makes this easier.
> Stakater reloader kubernetes addon

- .github/PULL_REQUEST_TEMPLATE.md
- Add a templated line for `Resolves #<xxx>` to help guide users to autolink issues to PRs 
- Add clarifying note on using existing examples to demonstrate addon usage and add a docs page when adding an addon
- Updating project general practices
> chore: Update PR template to ensure issue is linked and clarify when examples/docs should be added

- examples/karpenter/README.md
The examples/eks-cluster-with-karpenter/ directory doesn't exist.  Is it intended to be examples/karpenter/ ?
> This directory doesn't exist in the repo.

- docs/add-ons/argocd.md
- removes `argocd_admin_password_secret_name` from the docs
- `argocd_admin_password_secret_name` has been removed in https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/748 but wasn't removed in the docs.
> doc: remove argocd_admin_password_secret_name

- examples/node-groups/managed-node-groups/README.md
Several customers asking me about way to configure tags on MNG to scale from 0.
Just adding a workload example to showcase the existing configuration in the managed_node_groups example
> add workload example for spot scaling from 0 with MNG

- examples/eks-cluster-with-new-vpc/main.tf
- modules/kubernetes-addons/helm-addon/main.tf
Allow the user to set the `type` attribute within the `set` block of the `helm_release` resource if needed.
- Resolves #942 
I've updated the `eks-cluster-with-new-vpc` to prove it works, but noticed that `cert_manager_helm_config` is using `set_values` to …
> Support forcing type on Helm chart `set` attribute

- modules/kubernetes-addons/main.tf
When enabling external_secrets addon, it will deploy the helm chart regardless of what you configured through `argocd_manage_add_ons`. It should instead create only AWS IAM stuff and the namespace with the service account.
- Resolves #956
> Bugfix `argocd_manage_add_ons` not passed to `external_secrets` module

- docs/add-ons/cert-manager-csi-driver.md
- examples/eks-cluster-with-new-vpc/main.tf
- examples/tls-with-aws-pca-issuer/README.md
- examples/tls-with-aws-pca-issuer/main.tf
- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/cert-manager-csi-driver/README.md
- modules/kubernetes-addons/cert-manager-csi-driver/locals.tf
- modules/kubernetes-addons/cert-manager-csi-driver/main.tf
- modules/kubernetes-addons/cert-manager-csi-driver/outputs.tf
- modules/kubernetes-addons/cert-manager-csi-driver/variables.tf
- modules/kubernetes-addons/cert-manager-csi-driver/versions.tf
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/variables.tf
The cert-manager CSI driver can be used to generate and attach certificates and private keys directly to pods.
Add the Cert Manager CSI driver. Closes #950 
I would like to use this, with Cert Manager as it makes generating and mounting certificates for mTLS very easy.
> Add the cert-manager CSI driver

- modules/kubernetes-addons/karpenter/locals.tf
Updates karpenter to version 0.16.1.
[Version 0.16.1 ](https://github.com/aws/karpenter/releases/tag/v0.16.1)brings several bug fixes.
> chore(Karpenter version): upgrade Karpenter version to 0.16.1

- examples/eks-cluster-with-new-vpc/main.tf
Need to create a fixed set of instances for tests to pass.
Closes #972
> chore(e2e): fix for failing e2e test

- test/src/eks_blueprints_e2e_test.go
- sets terratest expected node to 3 
- following https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/973 the min-max-desired ASG set to 3, aligning Terratest to prevent terratest e2e failures.
> fix: terratest - expected eks node to 3

- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/versions.tf
- modules/launch-templates/README.md
- modules/launch-templates/versions.tf
- Pin Terraform version to `< 1.3.0` due to use of optional attribute experiment that was removed in `v1.3.0`
- Ref https://github.com/aws-ia/terraform-aws-eks-blueprints/actions/runs/3115601935/jobs/5052669371
- Closes #982
> fix: Pin Terraform version to `< 1.3.0` due to use of optional attribute experiment that was removed in `v1.3.0`

- .github/workflows/pr-title.yml
- Add PR title conventional commit format check
- Following the `squash and merge` pattern, our PR titles become the git commit description which is populated in the GitHub release log. Currently, we don't format our releases for conventional commits, but with this new workflow, we can ensure that PR titles follow conventional commits and better generate both the release name and release notes
Example of conventional commit title:
`feat: Add support for 'foo' addon`
Example of NOT conventional commit title:
`add Support for FOO addon`
> chore: Add PR title conventional commit format check

- modules/kubernetes-addons/karpenter/locals.tf
upgrades karpenter to [v0.16.2](https://github.com/aws/karpenter/releases/tag/v0.16.2)
consolidation enhancements
Unable to test it by running karpenter example because of incompatibility of this repo with terraform v1.3.0 (https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/635) . Will test it with older version on another machine. 
Update: 
tested karpenter example with terraform v1.2.9 using `sample_deployment_lt.yaml` and `sample_deployment.yaml`
and all 6 pods were successfully scheduled from both deployments.
Note that by default karpenter helm module …
> chore(addons/karpenter): Upgrade to 0.16.2

- README.md
- docs/core-concepts.md
- modules/aws-eks-fargate-profiles/README.md
- modules/aws-eks-managed-node-groups/README.md
- modules/aws-eks-self-managed-node-groups/README.md
- Using `latest` url in links to the gh pages to avoid using old versions of the gh pages.
- https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/987
> docs: Use latest links in gh pages

- .github/workflows/plan-examples.yml
- .github/workflows/pre-commit.yaml
- versions.tf
- Update runners to remove default Terraform version and use what we specify
- GitHub runners come with installed software by default, one of which is Terraform and this can cause conflicts on which version is used: the one the runner provides or the one we install via CI
> ci: Update runners to remove default Terraform version and use what we specify

- modules/irsa/main.tf
Signed-off-by: Fernando Miguel <github@FernandoMiguel.net>
increases IRSA timeout
- Resolves #1008
> fix: Increases IRSA timeout #1008

- modules/irsa/main.tf
To prevent namespace deletion before service account during the terrafrom destroy.
- Resolves #1012
> fix: IRSA module namespace and service account dependency

- modules/kubernetes-addons/helm-addon/main.tf
With 4.12 the default value of the `irsa_config` variable was changed from `null` to `{}` while the value of the `create_namespace` property within the `resource "helm_release" "addon"` was not updated and remained as:
```
var.irsa_config != null ? false : try(var.helm_config["create_namespace"], false)
```
The correct value should be:
```
var.irsa_config != {} ? false : try(var.helm_config["create_namespace"], false)
```
Versions comparison: https://github.com/aws-ia/terraform-aws-eks-blueprints/compare/v4.11.0...v4.12.0#diff-08ec4987c7b396bd22851dba98a35f66754059cbc09e6f88a0801533f8d03946R33
I was using v4.11.0, updated to v4.12.0, and spotted that the `create_namespace` value I wasn't overriding was suddenly changed from the default `true` to `false`.
**Note**: Not all the PRs require …
> fix: Helm-addon irsa_config default value for create_namespace condition

- modules/kubernetes-addons/locals.tf
external secrets are now available in git ops.
without it, git ops will not install external secrets.
> fix: Enable `external-secrets` support via GitOps and ArgoCD

- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/main.tf
- Update vault addon version to correct issue with default values data type
- Upstream fix is released now https://github.com/hashicorp/terraform-aws-hashicorp-vault-eks-addon/pull/10
- Resolves #1060 
> fix: Update vault addon version to correct issue with default values data type

- examples/crossplane/README.md
Instruction to list pods in `crossplane` namespace does not work, as the namespace created through blueprint is `crossplane-system`. 
This [minor] PR updates the Readme.md file to fix the specified namespace name to `crossplane-system`.
```shell
$ kubectl get pods -n crossplane
No resources found in crossplane namespace.
$ kubectl get pods -n crossplane-system
NAME                                             READY   STATUS    RESTARTS   AGE
aws-provider-f78664a342f1-b56dc7c4b-m2q49        1/1     Running   0          3m20s
crossplane-5696d784b8-26xps                      1/1     Running   0          5m57s
crossplane-rbac-manager-8466dfb7fc-4l8tr         1/1     Running   0          5m57s
jet-aws-provider-b42c59584ad8-6b4c7685dc-8bdj7   1/1     Running   0          3m41s
```
- This fix …
> chore: Fixed namespace doc for Crossplane Example

- examples/analytics/airflow-on-eks/main.tf
- examples/stateful/main.tf
- Replace EFS standalone resources with EFS module
- Resolves #1080
> chore: Replace EFS standalone resources with EFS module

- modules/launch-templates/templates/userdata-windows.tpl
The Windows self-managed node is being deployed with a secondary encrypted 50GB Amazon EBS disk as /dev/xvda, where the actual Userdata described in this script initializes the disk and formats but doesn't give any real usage. So, to enhance docker performance during node startup by avoiding concurrency disk I/O with the Operational system and image pulling, I'm proposing these additional lines in the scripts that set docker data to be stored on the secondary disk.
To help …
> fix: Windows - Changing docker files to be stored on secondary drive

- examples/eks-cluster-with-new-vpc/main.tf
Followed the getting started documentation with the `eks-cluster-with-new-vpc` example and the step
```
terraform apply -target="module.vpc"
```
failed with the error
```
│ Error: error creating EC2 NAT Gateway: NotAvailableInZone: Nat Gateway is not available in this availability zone
│ 	status code: 400, request id: 522ca79d-4c64-4b62-8be9-66b4d5b91014
│
│   with module.vpc.aws_nat_gateway.this[0],
│   on .terraform/modules/vpc/main.tf line 1025, in resource "aws_nat_gateway" …
```
> fix: Failed to create NAT gateway for `eks-cluster-with-new-vpc` example if local zones are enabled

- modules/kubernetes-addons/crossplane/locals.tf
Ensure the IRSA IAM roles are configured with the correct namespace scope.
Ensures the namespace of the crossplane IRSA IAM roles matches the namespace where the crossplane chart and resources are installed
- Resolves #1102 
> feat: Allow users to specify `namespace` for Crossplane addon

- examples/secrets-management/csi-secrets-driver/main.tf
- examples/secrets-management/csi-secrets-driver/versions.tf
- Add `kubectl` provider block to `csi-secrets-driver` example
- Resolves #1072
> fix: Add `kubectl` provider block to `csi-secrets-driver` example

- examples/ipv4-prefix-delegation/main.tf
- examples/vpc-cni-custom-networking/main.tf
- modules/kubernetes-addons/aws-coredns/main.tf
- Changed coredns local exec calls to base64 with flag `--decode` to `-d` which is supported universally on darwin & other linux distributions. 
- Resolves #1115 
- [n/a] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [n/a] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [n/a] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- A new docs page under `docs/add-ons/*` is required for new a new …
> fix: Changed non portable usage of base64 --decode flag to -d

- examples/tls-with-aws-pca-issuer/main.tf
- Adds missing k8s provider to the TLS example
- Adds depends on to wait for addons module
- k8s provider required otherwise will face the same localhost issues mentioned in the related issue.
- wait for addons to be deployed  first (let CRDs be created) before we try to create manifests that depends on CRDs
- Resolves https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1124
> fix: Add k8s provider & wait for addons

- examples/complete-kubernetes-addons/main.tf
- modules/kubernetes-addons/fargate-fluentbit/README.md
- modules/kubernetes-addons/fargate-fluentbit/locals.tf
- modules/kubernetes-addons/fargate-fluentbit/main.tf
Allows you to send fluent-bit process logs to CloudWatch.
This feature allows you to view the fluent bit process log in CloudWatch. The biggest benefit is being able to view the errors raised by the plugin. This new parameter is mentioned in the aws [documentation](https://docs.aws.amazon.com/pt_br/eks/latest/userguide/fargate-logging.html).
> feat: Add `flb_log_cw` parameter to Fargate FluentBit addon to enable sending logs to CloudWatch

- modules/kubernetes-addons/external-dns/main.tf
chore: tag external-dns aws_iam_policy
I like to tag stuff without the flaky default_tags aws provider option
> feat: Tag `external-dns` IAM policy

- main.tf
- Correct conditional logic check of cluster encryption config
- https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1132#discussion_r1014538322
> fix: Correct conditional logic check of cluster encryption config

- modules/kubernetes-addons/aws-ebs-csi-driver/main.tf
The irsa_iam_policies field has an impact on the role creation, via a count field. The try in this cause it to be unpredictable without a precursory apply. A lookup doesn't suffer from the same problem.
Fixes #1144
Makes the additional IAM policies a predictable input to the IRSA role `count` creation conditional check.
- Resolves #1144 
> fix: Additional IAM policy support for the aws-ebs-csi-driver addon role

- examples/gitops/argocd/main.tf
- examples/gitops/argocd/versions.tf
- adds custom bcrypt provider for argo example
Using custom bcrypt provider instead of the Hashicorp default one because the default generates a diff for every TF plan, leading to issues like https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1113 where the resources appears as changed every time. as mentioned in the [docs](https://registry.terraform.io/providers/viktorradnai/bcrypt/latest/docs/resources/hash): 
```
Unlike the built-in bcrypt function, this resource will not generate a diff unless the cleartext value changes.
```
- disables fluentbit CW log group creation by Terraform for Argo example
Consult the …
> fix: Use bcrypt for argo password, don't create cw log group

- .github/workflows/e2e-parallel-destroy.yml
- .github/workflows/e2e-parallel-full.yml
- removes crossplane from e2e GH workflows (parallel and destroy)
-
- Post https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1150 crossplane TF files doesn't exists in this repo therefore we can safety remove it from the e2e workflows.
> fix: Remove crossplane example from e2e workflows

- .github/workflows/e2e-parallel-full.yml
- main.tf
- Changes cleanup log group script to run 1 time as pre-requisite job in the workflow
- adds depends_on cluster readiness to the teams module
After reviewing last [e2e results](https://github.com/aws-ia/terraform-aws-eks-blueprints/actions/runs/3463906047/jobs/5784775725) noticed:
1) in multi tenancy example, terraform tries to create k8s resources before the cluster is healthy and ready (`healthz` endpoint returns 200), added depends_on to readiness data source.
2) in the …
> fix: E2E cleanup log group one time & wait for cluster readiness before creating teams k8s resources

- modules/kubernetes-addons/argocd/locals.tf
- modules/kubernetes-addons/argocd/values.yaml
This PR bumps argocd version to latest available (5.13.8) and also adds Resource Tracking to the `argocd-cm` ConfigMap.  We use the `annotation+label` option for tracking so that argocd uses annotation `argocd.argoproj.io/tracking-id` but we keep the label for components that still need compatibility with other tools that require the instance label. 
Latest version gives us the latest features and fixes including a fix that enables resource tracking of resources that are created as …
> feat: Bump argocd version

- modules/kubernetes-addons/locals.tf
adding support for me-central-1 region
I am deploying service in me-central-1 and found this issue hence trying to fix this on priority
> feat: Add support for `me-central-1` region

- docs/.pages
- docs/advanced/bottlerocket.md
- docs/core-concepts.md
- docs/node-groups.md
- Revert deletion of node groups docs
Post https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1104/files which lead to https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1142,  later on we reverted the node groups examples (https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1121) but forgot to revert the docs for the node groups.
- Use an existing example when possible to …
> docs: Revert node groups deletion

- modules/kubernetes-addons/cert-manager/main.tf
tags are not being applied policy created for cert manager irsa even when I pass the parameters.  See https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1216 for more info
This supports addition for tags for cert-manager-irsa policy created
I was trying to add tags to my cert-manager-irsa policy for least privilege but since there was no provision for tags I wasn't able to do that
- Resolves #1216
> fix: Added tags for cert-manager-irsa policy for issue #1216

- .pre-commit-config.yaml
- CODEOWNERS
- docs/add-ons/aws-node-termination-handler.md
- docs/core-concepts.md
- docs/node-groups.md
- modules/kubernetes-addons/aws-node-termination-handler/README.md
- modules/kubernetes-addons/aws-node-termination-handler/locals.tf
- modules/kubernetes-addons/aws-node-termination-handler/main.tf
- modules/kubernetes-addons/aws-node-termination-handler/outputs.tf
- modules/kubernetes-addons/aws-node-termination-handler/variables.tf
- modules/kubernetes-addons/locals.tf
- modules/kubernetes-addons/main.tf
Adds GitOps enablement for AWS Node Termination Handler as per.
- Resolves #1194
- https://github.com/aws-samples/eks-blueprints-add-ons/issues/32
Confirmed that main EKS Blueprints modules handle IAM/IRSA for NTH and hands off helm chart deployment to ArgoCD in a test EKS cluster deployed from forked local copies of this repo and eks-blueprints-add-ons.
Also updated the doc for NTH to include that it is intending to be used for EKS clusters with `self_managed_node_groups` as NTH shouldn't be necessary when using EKS `managed_node_groups` as per the comments in this …
> feat: Add gitops support for `aws-node-termination-handler`

- examples/fully-private-eks-cluster/add-ons/main.tf
Fix the fully-private-eks-cluster in example folder.
Since the feature #1033, cluster proportional autoscaler for CoreDNS is enabled by default. 
However, it downloads Helm chart from the internet which results in timeout failure for a fully private cluster. 
> fix: Disable proportional autoscaler for CoreDNS for fully private cluster

- examples/karpenter/main.tf
- modules/kubernetes-addons/karpenter/locals.tf
update karpenter to [v0.20.0](https://github.com/aws/karpenter/releases/tag/v0.20.0)
Improvements and fixes. Specially multi-node consolidation
Karpenter example deployment:
tested karpenter example with terraform v1.3.6 using `sample_deployment_lt.yaml` and `sample_deployment.yaml`
and all 6 pods were successfully scheduled from both deployments.
Note that karpenter only seems to work if we provision 2 managed nodes (one instance per node). It wasn't provisioning nodes with just one managed node (which is kind of strange since one pod of karpenter should also work in …
> chore: Update update `karpenter` addon to v0.20.0

- modules/launch-templates/templates/userdata-windows.tpl
Add ${bootstrap_extra_args} to windows launch template to allow pass in arguments directly to bootstrap, this feature exists in the linux launch template.
This enables customers to launch windows node in private subnets without internet access by pass in `-APIServerEndpoint <cluster-endpoint> -Base64ClusterCA <certificate-authority>` mentioned in [AWS Doc](https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html).
- Resolves #1239
> fix: Add ${bootstrap_extra_args} to windows launch template

- modules/kubernetes-addons/cert-manager/main.tf
- modules/kubernetes-addons/helm-addon/main.tf
Fix issue when tags are not being applied to IRSA roles created for ebs-csi drivers. See [issue 1249](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1249) for more info
- Resolves #1249
> fix: Add tags to IRSA created roles

- modules/kubernetes-addons/opentelemetry-operator/README.md
- modules/kubernetes-addons/opentelemetry-operator/variables.tf
Fixed a mistake in the description of the addon_config variable in the adot operator.
> fix: Fix a typo in a variable description

- modules/kubernetes-addons/consul/README.md
Fix a typo in URL which fails to render
within https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/add-ons/consul.md?plain=1
From "https://https://" to "https://" in
"For more details checkout [Consul](https://https://developer.hashicorp.com/consul/tutorials/get-started-kubernetes/kubernetes-gs-deploy) docs
- [ X] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ X] Yes, I ran `pre-commit run -a` with this PR
My first PR on this project.
> docs: Fix https://https:// in README

- examples/fully-private-eks-cluster/README.md
- examples/fully-private-eks-cluster/eks/variables.tf
Update default cluster version to 1.24 and removed unnecessary cluster version variable in tfvars.
> docs: Update fully private cluster example README

- outputs.tf
Distinguish between self-managed and EKS managed.
> chore: Minor typo on comments

- modules/kubernetes-addons/aws-load-balancer-controller/README.md
LB Ingress controller is the old name -> rename to AWS Load Balancer controller
> docs: Rename load balancer controller

- docs/add-ons/index.md
Hi folks I'm doing this PR because I was following the instructions to use eks_blueprints_kubernetes_addons module in this section --> https://aws-ia.github.io/terraform-aws-eks-blueprints/main/add-ons/ but when I was trying to deploy my add-ons I received the following error:
`╷
│ Error: Missing required argument
│
│   on ../../modules/eks_custom_networking/main.tf line 102, in module "eks_blueprints_kubernetes_addons":
│  102: module "eks_blueprints_kubernetes_addons" {
│
│ The …
> fix: Adding changes for support eks_cluster_id on add-ons documentation

- modules/kubernetes-addons/opentelemetry-operator/main.tf
With this PR I added required permissions for ADOT cluster role
I tried to use opentelemetry addon to install ADOT addon into EKS cluster and ran into issues
Than I checked what AWS requires for installing ADOT addon (https://amazon-eks.s3.amazonaws.com/docs/addons-otel-permissions.yaml) and figured out that there are several rules that are not in ClusterRole for opentelemetry. I cloned module and added them, after that I successfully installed ADOT into EKS 
> fix: Added required rules for adot cluster role

- modules/kubernetes-addons/csi-secrets-store-provider-aws/main.tf
What does this PR do?
Motivation
Trying to just leverage the csi secret store module to mount secrets to my main microservices
Resolves https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1172
> fix: Correcting namespace for csi-secret-store-provider-aws module

- .github/workflows/pr-title.yml
Update https://github.com/amannn/action-semantic-pull-request to latest available version
This fixes this warning
"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: amannn/action-semantic-pull-request@v4.5.0"
> chore: Update version of `amannn/action-semantic-pull-request` GitHub action

- modules/kubernetes-addons/karpenter/locals.tf
pdate karpenter to [v0.21.1](https://github.com/aws/karpenter/releases/tag/v0.21.1)
Improvements and fixes. Drift feature https://karpenter.sh/preview/concepts/settings/#feature-gates which is hard to test because of https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/512 (pass helm values without overriding/deleting default values)
Karpenter example deployment:
tested karpenter example with terraform v1.3.6 using sample_deployment_lt.yaml and sample_deployment.yaml
and all 6 pods were successfully scheduled from both deployments.
> feat: Update Karpenter to to `0.21.1`

- examples/fargate-serverless/README.md
- examples/fargate-serverless/main.tf
- examples/fargate-serverless/outputs.tf
- Update the `fargate-serverless` example to use the `terraform-aws-eks` module for cluster creation and EKS addons
- Simplify example now that EKS addons support custom configuration; demonstrate how CoreDNS can be patched for Fargate only clusters
- Updates examples to reflect latest features and patterns supported by Amazon EKS
> feat: Update `fargate-serverless` example to use the EKS module

- examples/analytics/emr-on-eks-fargate/main.tf
- examples/analytics/emr-on-eks-fargate/outputs.tf
- examples/analytics/emr-on-eks-fargate/versions.tf
- Update `emr-on-eks-fargate` example to use v19 of the EKS module
- Update example to patch CoreDNS addon for Fargate
- Keeps example aligned with current practices and features of Amazon EKS
> feat: Update `emr-on-eks-fargate` example to use v19 of the EKS module

- examples/ipv4-prefix-delegation/main.tf
- examples/ipv4-prefix-delegation/outputs.tf
- examples/ipv4-prefix-delegation/versions.tf
- Update `ipv4-prefix-delegation` example to use EKS v19 module
-  Keeps example aligned with current practices and features of Amazon EKS
> feat: Update `ipv4-prefix-delegation` example to use EKS v19 module

- examples/vpc-cni-custom-networking/README.md
- examples/vpc-cni-custom-networking/main.tf
- examples/vpc-cni-custom-networking/outputs.tf
- examples/vpc-cni-custom-networking/versions.tf
- Update `vpc-cni-custom-networking` example to use EKS v19 module
-  Keeps example aligned with current practices and features of Amazon EKS
> feat: Update `vpc-cni-custom-networking` example to use EKS v19 module

- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/main.tf
Update Sysdig addon to 0.0.3
Update the version of the Sysdig Addon from v0.0.1 to v0.0..3
- Point to the latest helm chart version and pin the last aws-ia framework version.
- [NA] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [NA] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [NA] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- A new docs page under `docs/add-ons/*` is required for …
> feat: Update Sysdig addon to v.0.0.3

- examples/gitops/argocd/main.tf
Fixes two typos within the examples/gitops/argocd/main.tf
> docs: Typo within gitops/argocd example

- examples/vpc-cni-custom-networking/main.tf
- Ensure only the 10.0.* subnet range is assigned to nodes for `vpc-cni-custom-networking` example
- Resolves #1313
- https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/a91b8409eac7442323de800584e762a525cde268#diff-c39da8e1f2726f8896d0ec2bb473a98f6e563d319802342dc59480b575d4aff4L61
> fix: Ensure only the 10.0.* subnet range is assigned to nodes for `vpc-cni-custom-networking` example

- examples/fargate-serverless/versions.tf
- examples/ipv4-prefix-delegation/versions.tf
- examples/ipv6-eks-cluster/versions.tf
- examples/karpenter/versions.tf
- examples/stateful/main.tf
- examples/stateful/outputs.tf
- examples/stateful/versions.tf
- examples/vpc-cni-custom-networking/main.tf
- examples/vpc-cni-custom-networking/versions.tf
- Upgrade `stateful` example to use v19 of EKS module
- Keeps example aligned with current practices and features of Amazon EKS
- Successfully provisioned but took two applies due to token timeout with use of static token in provider
> feat: Upgrade `stateful` example to use v19 of EKS module

- examples/ipv4-prefix-delegation/main.tf
- examples/vpc-cni-custom-networking/main.tf
Update example when using ipv4 prefix delegation to append the max pods values using KUBELET_EXTRA_ARGS to the bootstrap.sh flag to override the value provided by the EKS service.
When using managed groups with EKS and using the EKS default template, the service will calculate and pass the kubelet flag for max pods. 
- Resolves #1312
> fix: Append KUBELET_EXTRA_ARGS to bootstrap.sh default flags

- modules/kubernetes-addons/locals.tf
this will make the app of apps work for datadog.
> fix: Datadog not been managed by argocd

- examples/analytics/emr-on-eks-fargate/main.tf
- examples/fargate-serverless/README.md
- examples/fargate-serverless/main.tf
- examples/karpenter/main.tf
- Update serverless clusters running EKS Farage to maximize resource utilization on CoreDNS
- When running on EKS Fargate, pods are assigned Fargate task sizes that meet the resource request/limits specified. If a user requests values that are much lower than the closest task size, these resources will go to waste. Instead, users should calculate the request/limits they require, find the closest Fargate task size, and then increase their requests/limits to fit within that next closest task size to maximize resources that are provisioned. You can see the Fargate resource graduations here https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html
- Resolves #1327
- Use an existing example when …
> feat: Update serverless clusters running EKS Farage to maximize resource utilization on CoreDNS

- examples/vpc-cni-custom-networking/main.tf
`failure-domain.beta.kubernetes.io/zone` is deprecated. 
This change updates the `vpc-cni` configuration` ENI_CONFIG_LABEL_DEF=topology.kubernetes.io/zone`
https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html#custom-networking-configure-kubernetes
Keeping up with EKS 1.24
> chore: Update `ENI_CONFIG_LABEL_DEF` for VPC CNI to use current label spec

- modules/kubernetes-addons/aws-fsx-csi-driver/locals.tf
Bumping FSX CSI Driver to Version 0.9.0 (Helm version 1.5.0). This solves an issue with tagging of dynamically provisioned volumes (https://github.com/kubernetes-sigs/aws-fsx-csi-driver/issues/273)
Bumping FSX CSI Driver to Version 0.9.0 (Helm version 1.5.0). This solves an issue with tagging of dynamically provisioned volumes (https://github.com/kubernetes-sigs/aws-fsx-csi-driver/issues/273)
- Resolves FSX CSI Driver issue …
> feat: Bumping FSX CSI Driver to Version 0.9.0

- README.md
- docs/add-ons/managed-add-ons.md
- modules/kubernetes-addons/aws-coredns/main.tf
- modules/kubernetes-addons/aws-ebs-csi-driver/main.tf
- modules/kubernetes-addons/aws-kube-proxy/main.tf
- modules/kubernetes-addons/aws-vpc-cni/main.tf
- versions.tf
- Adding new `configuration_values` field to EKS Managed addons. This feature allows users to modify the addon config values during the creation and update. See the [link](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon#example-add-on-usage-with-custom-configuration_values) for more details
Closes #1401
- Use an existing example when possible …
> feat: Adding `configuration_values` support to Managed EKS add-ons

- .github/scripts/plan-examples.py
- Correcting example folder path to exclude for terraform plan CI check.
- PRs showing failure on CI because the terraform plan action is not skipping the blue-green-route53 example properly.
examples:
https://github.com/aws-ia/terraform-aws-eks-blueprints/actions/runs/4078739311/jobs/7029677318
https://github.com/aws-ia/terraform-aws-eks-blueprints/actions/runs/4013393770/jobs/6923388512
- Use an existing …
> fix: Exclude correct example folder path

- modules/aws-eks-teams/README.md
- modules/aws-eks-teams/main.tf
- modules/aws-eks-teams/variables.tf
Adds an optional path variable for the `platform_team_eks_access` `aws_iam_policy`.
Needed a custom path for the resource aws_iam_policy.platform_team_eks_access, since the roles used to deploy the resources have strict permissions on certain policy paths.
> feat: Add optional path variable for the platform_team_eks_access aws_iam_policy

- examples/ipv4-prefix-delegation/main.tf
- examples/vpc-cni-custom-networking/main.tf
- Use `most_recent = true` when using VPC CNI custom configuration
- Without using the most recent, the default version of the VPC CNI pulled may or may not have support for the environment variable versions used. This ensures that the latest addon version is used which has access to all of the environment variables used in the examples
> fix: Use `most_recent = true` when using VPC CNI custom configuration

- examples/fully-private-cluster/README.md
Add missing targets (`vpc_endpoints` and `vpc_endpoints_sg` ) to deploy in README
Lead readers to deploy `fully-private-cluster` example successfully
I tried this edited command and confirmed that it is OK.
> chore: Add missing targets to `terraform apply` in `fully-private-cluster` example README

- examples/karpenter/main.tf
- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/karpenter/README.md
- modules/kubernetes-addons/karpenter/data.tf
- modules/kubernetes-addons/karpenter/locals.tf
- modules/kubernetes-addons/karpenter/main.tf
- modules/kubernetes-addons/karpenter/outputs.tf
- modules/kubernetes-addons/karpenter/variables.tf
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/variables.tf
> feat: Added SQS queue creation with events for Karpenter 

- docs/.pages
- docs/core-concepts.md
As part of v5 migration, https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1428 removes "Node Groups" page, but forgot to remove the page button.
This PR removes the "Node Groups" button in the documentation page.
Also, new users likely lost what to do when configuring a cluster.
We at least need to mention that we use `terraform-aws-modules/eks/aws` to avoid confusion.
> docs: Remove "Node Groups" section and mention `terraform-aws-modules`

- examples/stateful/README.md
- examples/stateful/main.tf
- Update `stateful` example to demonstrate: 
- Multiple volumes; second volume to be dedicated to the `containerd` runtime
- Instance store with mountaing via user data
- Setting EBS volume storage type `gp3`
- EBS volume encryption using CMK (customer managed KMS key)
- Add `gp3` storage class and setting as the default storage class provider
- Resolves #1261
> feat: Update `stateful` example to show multi-volume, instance store, gp3, encryption, and containerd dedicated volume

- docs/add-ons/crowdstrike-falcon.md
add the `crowdstrike-falcon` partner documentation
Make it easy to boostrap falcon in AWS EKS
- [n/a] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [n/a] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
Below is the result of running the `crowdstrike-falcon` example
`kubectl` of the operator and KPA
> feat: Add `crowdstrike-falcon` addon

- modules/kubernetes-addons/external-dns/data.tf
If you have multiple Route 53 zones on the AWS account, then externalDNS will fail trying to list the resource record sets for other hosted zones (not the one used by your cluster) and won't be able to update even the entry for the zone it has access to.
The issue has appeared after this commit by @rodrigobersa : https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/8421a3b9600b734e600039ec2e8cddf6d03afe83#diff-3972dd5c24a63dda22823ec8ba870f9c566791eeffef91eaa6d6c382fd3fd9d3L97 
So this pull request basically reverts the policy body to the earlier version.
- Ref aws-ia/terraform-aws-eks-blueprints-addons#17
I've created a new EKS cluster using my fork and the policy was created correctly:
```
{
"Statement": [
{
"Action": "route53:ChangeResourceRecordSets",
"Effect": "Allow", …
```
> fix: Update `ExternalDNS` policy to support multiple Route 53 zones

- modules/irsa/main.tf
> fix: Ignore metadata changes on IRSA created namespace for GitOps approach

- modules/kubernetes-addons/argocd/variables.tf
This fixes a recent change that broke the argocd addon variables file -- i escaped the backslash before the dot so that it's a valid regex.
> fix: Escape regex validation backslash

- modules/kubernetes-addons/argocd/variables.tf
- Remove variable validation - its causing more issues than value
- Resolves #1520
> fix: Remove variable validation - its causing more issues than value

- examples/blue-green-upgrade/modules/eks_cluster/main.tf
- modules/kubernetes-addons/README.md
- modules/kubernetes-addons/main.tf
- modules/kubernetes-addons/ondat/README.md
- modules/kubernetes-addons/ondat/main.tf
- modules/kubernetes-addons/ondat/outputs.tf
- modules/kubernetes-addons/ondat/values.yaml
- modules/kubernetes-addons/ondat/variables.tf
- modules/kubernetes-addons/ondat/versions.tf
- Add local copy of Ondat due to Ondat repository migration
- Resolves #1522
> fix: Add local copy of Ondat due to Ondat repository migration

- modules/kubernetes-addons/csi-secrets-store-provider-aws/main.tf
- modules/kubernetes-addons/secrets-store-csi-driver/locals.tf
Fixes an issue with AWS CSI Secrets Provider when using the default namespace and also updates the chart because of deprecation notice on EKS charts repo
- Resolves #1355 
- [] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
> fix: Update CSI Secrets Provider driver

- modules/kubernetes-addons/aws-for-fluentbit/locals.tf
- modules/kubernetes-addons/aws-for-fluentbit/values.yaml
- modules/kubernetes-addons/aws-node-termination-handler/locals.tf
Upgrades modules
- Will eventually resolve [#1456]
- Not every module is tested so there could be other modules. 
This list can be updated and I or someone else can update those modules. Do we have an example that I can run to test all modules?
Tested by 
1. deploying `examples/karpenter`. 
2. Upgrading it to 1.25
3. Installing above mentioned modules
> feat: Upgrade modules for EKS 1.25 support

- main.tf
- variables.tf
Adds flag for creating primary security group tags.
- Resolves #1563
> feat: Add security group tag creation flag

- modules/kubernetes-addons/karpenter/locals.tf
Updates the default karpenter version fixing connectivity issues for Bottlerocket nodes on IPv6 clusters 
- [Resolves #<issue-number>](https://github.com/aws/karpenter/issues/3623)
> feat: Update Karpenter version to `0.27.3`

- docs/add-ons/index.md
A simple correction on documentation. The [documentation](https://aws-ia.github.io/terraform-aws-eks-blueprints/main/add-ons/) says:
> Enable the ArgoCD add-on by setting `argocd_enable` to `true`.
but the actual variable is `enable_argocd`
> docs: Fix wrong variable name

- data.tf
- locals.tf
Helps to aws_caller_identity returns a consistent value when using assumed-role credentials
[Issue 1393](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1393)
- Resolves #1393
> fix: Add aws_iam_session_context issuer_arn as local aws_caller_identity

- modules/kubernetes-addons/datadog-operator/main.tf
Update the datadog-operator Helm chart version to 1.0.2.
The latest version of the datadog-operator Helm chart is [1.0.2](https://github.com/DataDog/helm-charts/releases/tag/datadog-operator-1.0.2).
The version of the datadog-operator Helm chart referenced in the add-on is currently 0.8.8. This version relies on policy/v1beta1 `PodDisruptionBudget` which was deprecated in Kubernetes v1.21 and removed from Kubernetes v1.25. In addition to new features, version 1.0.0 of the chart [resolves this issue](https://github.com/DataDog/helm-charts/issues/941).
> feat: Update datadog-operator chart to 1.0.2

- modules/aws-eks-managed-node-groups/locals.tf
- modules/aws-eks-managed-node-groups/managed-launch-templates.tf
Parameterize `update_default_version` launch template config so nodegroups are not automatically updated on a version change
https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1589
Allow more control over Prod maintenance activities
> feat: Nodegroup `update_default_version` config should be parameterized

- docs/add-ons/kubecost.md
- modules/kubernetes-addons/kubecost/main.tf
- modules/kubernetes-addons/kubecost/values.yaml
EKS version 1.25+ breaks cost-model container
issue makes pod unhealthy because of error:
```
HorizontalPodAutoscaler v2beta1 is deprecated
```
ref: https://github.com/tektoncd/pipeline/issues/5128
Bumps container tag for cost-model that has the new HPA ApiVersion support with EKS version 1.25+. Without it, container is never in healthy state by kubelet.
related to this: https://github.com/tektoncd/pipeline/issues/5128
- [X ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
> fix: Kubecost Container Version health with EKS 1.25+

- modules/aws-eks-managed-node-groups/templates/userdata-amazonlinux2eks.tpl
fix: the typo in userdata-amazonlinux2eks.tpl.
Within the code, the content '%{if length(service_ipv4_cidr) > 0 ~ }' should be changed to '%{if length(service_ipv6_cidr) > 0 ~ }'. Currently, when service_ipv4_cidr is defined in the userdata, the condition 'export SERVICE_IPV6_CIDR=${service_ipv6_cidr}' is executed.
> fix: The typo in userdata-amazonlinux2eks.tpl

- examples/do-not-use/docs/gatekeeper.md
- examples/do-not-use/docs/nginx.md
- examples/do-not-use/docs/velero.md
- examples/do-not-use/docs/vpa.md
- examples/do-not-use/variables.tf
As part of testing v5 modules modules gatekeeper and vpa
As part of testing v5
> feat: Update v5 docs for gatekeeper, vpa, nginx

- examples/wireguard-with-cilium/README.md
- examples/wireguard-with-cilium/destroy.sh
- examples/wireguard-with-cilium/main.tf
- examples/wireguard-with-cilium/versions.tf
Update the wireguard-with-cilium example
- Use latest EKS 1.27
- Use latest Cilium 1.13.2
- Update validate instructions to check if data from nginx example is going over wireguard tunnel avoid false positive.
- Add delay after cilium helm install for example pods to communicate using encryption, without this delay the pods will communicate over http (ie security group not created) and not use the wireguard tunnel
- Add security group ingress rule for node to node to allow wireguard traffic to flow using `udp/51871`
There is still some investigation if someone wants to pick up on why the 15s delay is need it. One theory is that cilium is reporting ready to helm (via probes) but is not done being completed setup.
- Resolves #1618
> fix: Update wireguard-with-cilium example

- examples/multi-tenancy-with-teams/main.tf
The readme says 2 namespaces team-blue and team-red will be created, but the code has some hardcoded values instead of using the key from the iterator
> fix: Correct `teams` patterns use of multi-team namespace creation

- examples/fargate-serverless/README.md
Removes the link as the sample-app is provided inline.
- Resolves #1678
> fix: Remove broken link in fargate-serverless README

- examples/vpc-cni-custom-networking/main.tf
When using custom networking, whatever security groups you specify in the ENIConfigs will be attached to your EKS Nodes (or at least Managed Node Groups in my experience). This example does _not_ use the EKS-created cluster security group in the node's launch template, but _does_ specify it in the ENI Config. The result is that EKS will attach the EKS Cluster SG to the node which is likely not the desired outcome. 
This issue can be seen previously here in this issue: https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1390
The [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#i-received-an-error-expect-exactly-one-securitygroup-tagged-with-kubernetesioclustername-) referenced also has some inaccuracies in it:
1) By having the tag in place …
> fix: Remove cluster security group from EniConfig for Custom Networking example

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/dependency-review.yml
- .pre-commit-config.yaml
- examples/blue-green-upgrade/environment/versions.tf
- examples/fargate-serverless/README.md
- examples/fargate-serverless/main.tf
The fargate sample could not be deployed correctly, so it has been partially fixed.
Using Karpenter's example, the creation of the Blueprints add-on was delayed until after the creation of the Fargate profile.
> fix: Modify Fargate serverless example to wait for Fargate profiles to provision

- .github/workflows/publish-docs.yml
- Update doc publish workflow permissions
- I'm not sure what changed, but the workflow is encountering a [permissions denied](https://github.com/aws-ia/terraform-aws-eks-blueprints/actions/runs/5645948474/job/15293055425) error and I am hoping this corrects it
> fix: Update doc publish workflow permissions

- docs/blueprints/aws-eks-privatelink.md
- docs/blueprints/privatelink-access.md
- Correct doc name for privatelink example
- The pattern name changed during the recent PR review, but the documentation page/link was not updated to match
> fix: Correct doc name for privatelink example

- examples/istio/main.tf
Changed addons to blueprint
Changing the addons from EKS to EKS Blueprints Addons fixed error messagens on vpc-cni.
> fix: Change EKS addons to use EKS Blueprint addons module

- examples/blue-green-upgrade/modules/eks_cluster/main.tf
> fix: Keep multi-repo consistent with single-repo for helm values configuration.

- .github/scripts/plan-examples.py
- examples/privatelink-access/README.md
- examples/privatelink-access/privatelink.tf
The eventbridge target for the rule `eks-api-endpoint-create` wasn't getting created with the first `terraform apply` command and it doesn't get created until after the EKS cluster is completely setup causing the initial ENI create events to be missed.
This PR ensures that the first  `terraform apply` command:
1.  Includes the target `module.eventbridge` that takes care of creating both modules `module.create_eni_lambda` and `module.delete_eni_lambda`
2. For the above to be possible, it removes the dependency of `module.delete_eni_lambda` on `module.eks`
> fix: Enable EventBridge rules/targets before EKS cluster

- .pre-commit-config.yaml
- docs/blueprints/istio-multi-cluster.md
- examples/istio-multi-cluster/README.md
- Correct doc title to distinguish between the two Istio patterns
- This change aligns the sidebar and page titles with the blueprint name
- Validated by running `mkdocs serve` locally
> fix: Correct doc title to distinguish between the two Istio patterns

- README.md
- docs/faq.md
- docs/getting-started.md
- Update getting-started and main README.md documentation
- Clarify the consumption model of EKS Blueprints and help users understand how they should think about using and interacting with the project
- Clarify the Terraform caveats that have been raised by users
- Provide standard `deploy`/`destroy` documentation in the getting started guide so that we can reduce the amount of boilerplate in the pattern's documentation (next PR)
> docs: Update getting-started and main README.md documentation

- patterns/istio/README.md
Correction to embedded YAML in Istio pattern
Embedded YAML had formatting errors
None
> docs: Correction to embedded YAML in Istio pattern

- .github/workflows/publish-docs.yml
- .pre-commit-config.yaml
- README.md
- docs/_partials/destroy.md
- docs/getting-started.md
- patterns/agones-game-controller/README.md
- patterns/appmesh-mtls/README.md
- patterns/argocd/README.md
- patterns/blue-green-upgrade/modules/eks_cluster/README.md
- patterns/elastic-fabric-adapter/README.md
- patterns/external-secrets/README.md
- patterns/fargate-serverless/README.md
- patterns/fully-private-cluster/README.md
- patterns/ipv6-eks-cluster/README.md
- patterns/istio/README.md
- patterns/karpenter/README.md
- patterns/multi-tenancy-with-teams/README.md
- patterns/private-public-ingress/README.md
- patterns/privatelink-access/README.md
- patterns/sso-iam-identity-center/README.md
- patterns/sso-okta/README.md
- patterns/stateful/README.md
- patterns/tls-with-aws-pca-issuer/README.md
- patterns/wireguard-with-cilium/README.md
- Update mkdocs CD deploy to use standard mkdocs without versioning
- Correct links with change to drop versioned docs
- Only v5 documentation will be shown to avoid confusion. If users need to view v4.x configurations, that is captured in git history and accessible through the repository using the tag version
> chore: Update mkdocs CD deploy to use standard mkdocs without versioning

- patterns/istio/README.md
- patterns/istio/main.tf
- Both the `istio-base` and `istiod` rely on the `istio-system` namespace, but if we try to create it in the `helm_release` resource then the chart that is not creating the namespace fails since the namespace does not exist. Instead, changing to use a standalone namespace resource that is passed into the charts resolves this conflict
- The `istio-ingress` automatically pulls the necessary image but only after it has been updated by `istiod` to know which image it should pull. This creates a hard dependency where `istio-ingress` requires `istiod` to be running before its pods are created, otherwise an image value must be specified in the `instio-ingress` chart values. There are numerous issues for this unfortunate situation, see below a couple of references. To get around this, the …
> fix: Use namespace resource to share across `istio` charts to avoid conflicts

- patterns/stateful/README.md
would be line 45 of the stateful readme had a link to content which no long existed. [readme](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/stateful/README.md?plain=1)
I migrated the content from the old page to a "Validate Velero" section and updated the current Validation area to be to focused on validation of local storage attachment. 
> docs: Updated Stateful Pattern Readme to include validation of Velero

- patterns/blue-green-upgrade/README.md
Fixes the documentation for blue/green eks example
I was following the docs and saw an error
- [ x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [  ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [  ] Yes, I ran `pre-commit run -a` with this PR
> docs: Fix typo/bug in readme

- patterns/elastic-fabric-adapter/main.tf
- patterns/elastic-fabric-adapter/versions.tf
- User data has been updated to check if EFA driver has been installed and skills installing the EFA driver. Starting with EKS v1.28, the EKS GPU AMI now comes with the EFA driver installed
- A note  has been added that the preferred method is to install the EFA driver on the AMI instead of during provisioning
- The previous command `fi_info -p efa -t FI_EP_RDM` was failing since the `fi_info` executable is not located on the PATh yet (requires a reboot). Instead, we can use the full path to the executable to get around this
- The EFA device plugin has been converted to a Terraform daemonset to drop the use of the `kubectl` provider
- Current pattern is throwing an error and preventing nodes from joining since it errors out on `fi_info -p efa -t FI_EP_RDM` and never reaches the bootstrap …
> fix: Ensure EFA installer uses full path to EFA bin and does not install if already present

- patterns/privatelink-access/lambdas/create_eni.py
- patterns/privatelink-access/lambdas/delete_eni.py
This PR fixes the broken/non-functional logging in the Lambda functions of the `privatelink-access` pattern. 
- Resolves #1798 
None
> fix: Fix logging for Lambda functions in the `privatelink-access` pattern

- .github/workflows/plan-examples.yml
- Remove `pull_request_target` from plan examples workflow
- N/A
- Issue opened to track the replacement for this https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1807
> chore: Remove `pull_request_target` from plan examples workflow

- patterns/istio/README.md
- patterns/istio/main.tf
Additional annotation was required below for the Service of `Type=LoadBalancer` to be picked by AWS Loadbalancer Controller regardless of whether the AWS Load Balancer Controller was created later than the Service itself.
`"service.beta.kubernetes.io/aws-load-balancer-nlb-target-type" = "ip"`
- Resolves #1793
> fix: Additional annotation added for NLB in `istio` pattern

- modules/kubernetes-addons/aws-load-balancer-controller/data.tf
- Resolves Issue where the policy for load balancer controller is exceeding the 6144 character limit 
```
│ Error: updating IAM Policy (arn:aws-cn:iam::123456789:policy/cn-northwest-1-cluster-lb-irsa): LimitExceeded: Cannot exceed quota for PolicySize: 6144
│       status code: 409, request id: 160721f9-bf36-4e4f-a085-788b3e8dc5ab
│ 
│   with module.eks_cluster.module.kubernetes_addons.module.aws_load_balancer_controller[0].aws_iam_policy.aws_load_balancer_controller,
│   on .terraform/modules/eks_cluster.kubernetes_addons/modules/kubernetes-addons/aws-load-balancer-controller/main.tf line 10, in resource "aws_iam_policy" "aws_load_balancer_controller":
│   10: resource "aws_iam_policy" "aws_load_balancer_controller" {
```
apply the recommended policy : …
> Apply the Recommended Load balancer controller policy to v4

- patterns/blue-green-upgrade/modules/eks_cluster/outputs.tf
- patterns/blue-green-upgrade/modules/eks_cluster/versions.tf
- removed deprecated, unused hashicorp/template provider
- removed the comments in output
- the hashicorp/template provider is deprecated
and not supported in m1 macos
- ref. https://discuss.hashicorp.com/t/template-v2-2-0-does-not-have-a-package-available-mac-m1/35099
- also the provider is not used in the module
- it seems was added at #1769(2e09cf8) for debugging
- the output for debugging is commented out; not used
- Resolves #1841
- tested, it works
Signed-off-by: flavono123 <flavono123@gmail.com>
> fix: Remove unused hashicorp/template provider

- patterns/istio/README.md
Added step to manually uninstall `istio-ingress` helm release before destroy steps. Fixes #1843
- Resolves #1843
> fix: Add uninstall before destroy (#1843)

- patterns/istio/main.tf
Updating the EKS version to 1.28 and Istio chart version to 1.20.2
End of life for 1.81 version from Jan 4, 2024. Check here
<br class="Apple-interchange-newline">
- [ X] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [X ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [X ] Yes, I ran `pre-commit run -a` with this PR
> feat: Updating the EKS and Istio version

- patterns/istio/README.md
- patterns/istio/main.tf
Updating readme for installation of Kiali which is Istio Addon for observability for Istio version 1.20
End of life for 1.81 version from Jan 4, 2024. 
- [X ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ X] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ X] Yes, I ran `pre-commit run -a` with this PR
> feat: Updating readme for installation of latest Istio Addon for Kiali

- patterns/istio-multi-cluster/README.md
Update spelling in README to make it easier to read.
> fix: Spelling corrections in Istio-multi-cluster README

- docs/_partials/destroy.md
- patterns/agones-game-controller/main.tf
- patterns/appmesh-mtls/main.tf
- patterns/aws-vpc-cni-network-policy/main.tf
- patterns/elastic-fabric-adapter/main.tf
- patterns/external-secrets/main.tf
- patterns/fargate-serverless/main.tf
- patterns/istio/main.tf
- patterns/kubecost/main.tf
- patterns/private-public-ingress/main.tf
- patterns/stateful/main.tf
- patterns/tls-with-aws-pca-issuer/main.tf
- patterns/vpc-lattice/client-server-communication/eks.tf
- patterns/wireguard-with-cilium/eks.tf
- Map the Terraform entity into the cluster as admin to allow deploying Kubernetes, Helm, and Kubectl resources via providers
- The entity that is executing Terraform commands needs to have access inside the cluster to allow the Kubernetes, Kubectl, and Helm providers to provision the resources they create. Prior to cluster access entry, Terraform was automatically granted these permissions because it was the cluster creator.
> fix: Map the Terraform entity into the cluster as admin to allow deploying Kubernetes, Helm, and Kubectl resources via providers

- patterns/gitops/getting-started-argocd/main.tf
- patterns/gitops/getting-started-argocd/variables.tf
- patterns/gitops/multi-cluster-hub-spoke-argocd/README.md
- patterns/gitops/multi-cluster-hub-spoke-argocd/hub/bootstrap/workloads.yaml
- patterns/gitops/multi-cluster-hub-spoke-argocd/hub/main.tf
- patterns/gitops/multi-cluster-hub-spoke-argocd/spokes/deploy.sh
This change makes it more clear how the bootstrap of addons and workloads happens, by removing the use of gitops-bridge module to deploy the bootstrap ArgoCD apps.
This change should make it more clearn to the end user trying out the pattern and following step by step the instructions in the README.md of each corresponding gitops pattern.
- Resolves #1882
> feat: Make gitops-bridge example to use kubectl to deploy addons and workloads

- .pre-commit-config.yaml
- docs/cSpell_dict.txt
- patterns/appmesh-mtls/versions.tf
- patterns/external-secrets/main.tf
- patterns/external-secrets/versions.tf
- patterns/multi-tenancy-with-teams/main.tf
- patterns/multi-tenancy-with-teams/versions.tf
- patterns/tls-with-aws-pca-issuer/versions.tf
- Replace unmaintained kubectl provider with an updated fork. We can continue to look at replacing the use of Kubernetes providers from Terraform, but this at least resolves the issue with the defunct provider 
- Resolves #1675
> fix: Replace un-maintained kubectl provider with an updated fork

- patterns/privatelink-access/README.md
- patterns/privatelink-access/eks.tf
- patterns/privatelink-access/outputs.tf
Refactored the pattern to use the IAM access entries instead of using `aws-auth` configmap.
- Resolves #1816
> refactor: Updated code with IAM access entries

- docs/patterns/vpc-lattice/client-server-communication.md
- mkdocs.yml
- patterns/vpc-lattice/client-server-communication/README.md
The VPC lattice pattern documentation was not showing properly, this fix it.
> docs: Fix vpc lattice pattern doc

- patterns/karpenter/main.tf
Replaced `aws-auth` entries with access entries
> refactor: Replaced aws-auth ConfigMap entries with access entries

- patterns/sso-iam-identity-center/README.md
- patterns/sso-iam-identity-center/outputs.tf
It was hard at a first hand to understand what was going wrong and how to use the pattern.
This small improvment makes clearer what needs to be checked
> chore: Improve sso output

- .github/workflows/publish-docs.yml
- .pre-commit-config.yaml
- docs/patterns/ml-capacity-block.md
- patterns/ml-capacity-block/README.md
- patterns/ml-capacity-block/eks.tf
- patterns/ml-capacity-block/main.tf
- patterns/nvidia-gpu-efa/README.md
- patterns/targeted-odcr/README.md
- patterns/targeted-odcr/eks.tf
- Add pattern that demonstrates using ML capacity block reservation with self-managed node group
- Demonstrate how customers can use CBRs with EKS today; will update at later day to use EKS managed node group when that support is added to the service
In draft mode pending https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3030
> feat: Add pattern that demonstrates using ML capacity block reservation with self-managed node group

- docs/patterns/karpenter-mng.md
- docs/patterns/karpenter.md
- patterns/karpenter-mng/README.md
- patterns/karpenter-mng/eks.tf
- patterns/karpenter-mng/example.yaml
- patterns/karpenter-mng/karpenter.yaml
- patterns/karpenter-mng/main.tf
- patterns/karpenter-mng/vpc.tf
- patterns/karpenter/README.md
- Add Karpenter on EKS managed node group with EKS Pod Identity and cluster access entry
- This demonstrates how customers can run Karpenter on EKS managed node group, as well as how to utilize EKS Pod Identity for the controller's permissions
- This also highlights the various components that are required to thread throughout resources for discoverability by the controller
> feat: Add Karpenter on EKS managed node group with EKS Pod Identity and cluster access entry

- patterns/karpenter-mng/README.md
- patterns/karpenter-mng/eks.tf
- Update Karpenter MNG pattern to use updated module w/ pod identity association included following https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3031
- Simplifies configuration used
> chore: Update Karpenter MNG pattern to use updated module w/ pod identity association included

- patterns/ml-capacity-block/README.md
- patterns/ml-capacity-block/eks.tf
- patterns/ml-capacity-block/helm.tf
- patterns/ml-capacity-block/main.tf
- patterns/nvidia-gpu-efa/README.md
- patterns/nvidia-gpu-efa/eks.tf
- patterns/nvidia-gpu-efa/helm.tf
- patterns/nvidia-gpu-efa/main.tf
- patterns/targeted-odcr/README.md
- patterns/targeted-odcr/eks.tf
- patterns/targeted-odcr/helm.tf
- patterns/targeted-odcr/main.tf
- Update targeted ODCR to show p5 to be reflect current usage
- Remove t3 capacity reservations and require reservation ARN be passed in via variable
- Show usage with NVIDIA GPU instance and EFA which is the common use case today
- Add pod identity agent - start making it a standard on patterns
- Split out Helm charts to separate file to allow importing into docs site when necessary
- Add kubectl output per usual
- While its great to have a pattern that can be deployed and see the reservations, etc. - it did not reflect the current target audience (p4/p5 users with EFA), which led to confusion. This updates the pattern to better reflect what the majority would be using today with capacity allocated in targeted ODCRs (tl;dr - meeting users where they are)
> chore: Update targeted ODCR to show p5 to be reflect current usage

- .pre-commit-config.yaml
- docs/cSpell_dict.txt
- patterns/agones-game-controller/main.tf
- patterns/aws-vpc-cni-network-policy/main.tf
- patterns/external-secrets/main.tf
- patterns/fargate-serverless/main.tf
- patterns/fully-private-cluster/main.tf
- patterns/ipv6-eks-cluster/main.tf
- patterns/istio/main.tf
- patterns/karpenter-mng/eks.tf
- patterns/karpenter/main.tf
- patterns/kubecost/main.tf
- patterns/ml-capacity-block/eks.tf
- patterns/nvidia-gpu-efa/eks.tf
- patterns/private-public-ingress/main.tf
- patterns/privatelink-access/eks.tf
- patterns/sso-iam-identity-center/main.tf
- patterns/sso-okta/main.tf
- patterns/stateful/main.tf
- patterns/targeted-odcr/eks.tf
- patterns/tls-with-aws-pca-issuer/main.tf
- patterns/vpc-lattice/client-server-communication/eks.tf
- patterns/wireguard-with-cilium/eks.tf
- Update EKS version to 1.30 where applicable
- EKS released support for 1.30
> chore: Update EKS version to 1.30 where applicable

- .pre-commit-config.yaml
- patterns/karpenter-mng/eks.tf
- Remove referenc to enable EFA on Karpenter MNG example
- Copy+paste error, this does not belong in this pattern
> chore: Remove referenc to enable EFA on Karpenter MNG example

- .pre-commit-config.yaml
- patterns/ml-capacity-block/README.md
- patterns/ml-capacity-block/eks.tf
- patterns/ml-capacity-block/helm.tf
- patterns/ml-capacity-block/main.tf
- patterns/nvidia-gpu-efa/eks.tf
- patterns/nvidia-gpu-efa/helm.tf
- patterns/targeted-odcr/eks.tf
- patterns/targeted-odcr/helm.tf
- Update ML CBR example to use EKS managed node group
- Upstream support added in `v20.17.0` https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3091 
- Update EFA device plugin to latest
- Update EKS module to latest on GPU patterns
- ML CBR is a now supported in EKS managed node group(s) https://aws.amazon.com/about-aws/whats-new/2024/07/amazon-eks-natively-ec2-capacity-blocks-for-ml/
- Tested and validated with `t3.small` CBR
> feat: Update CBR example to use EKS managed node group

- patterns/karpenter-mng/eks.tf
- patterns/karpenter-mng/main.tf
- Resolves #1984 
The fix is similar to what have been done on EKS module : https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3097
> fix: Only tag cluster node security group for Karpenter

- patterns/bottlerocket/addons.tf
- patterns/bottlerocket/main.tf
- patterns/karpenter-mng/main.tf
- patterns/karpenter/main.tf
- Updated AWS provider configuration to use alias 'ecr' and hardcode the region to 'us-east-1' for ECR authentication in patterns that use public ECR images and require authentication.
- The intention is to keep the consistency in all repositories. This change ensures clear documentation and prevents users from mistakenly altering the region. 
- [] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [] Yes, I ran `pre-commit run -a` with this PR
There is a provider here [link](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/1975b53c9ebe5f8dcde979ccdae3d87dcb5e43cd/patterns/blue-green-upgrade/modules/eks_cluster/main.tf#L1C1-L5C2) with the old format, but it's not being used, so I didn't change it. Is it ok to …
> chore: Update AWS provider to 'ecr' for ECR authentication

- patterns/agones-game-controller/main.tf
- patterns/aws-vpc-cni-network-policy/main.tf
- patterns/blue-green-upgrade/environment/main.tf
- patterns/blue-green-upgrade/modules/eks_cluster/main.tf
- patterns/bottlerocket/addons.tf
- patterns/bottlerocket/main.tf
- patterns/ecr-pull-through-cache/main.tf
- patterns/external-secrets/main.tf
- patterns/fargate-serverless/main.tf
- patterns/fully-private-cluster/main.tf
- patterns/gitops/getting-started-argocd/main.tf
- patterns/gitops/multi-cluster-hub-spoke-argocd/hub/main.tf
- patterns/gitops/multi-cluster-hub-spoke-argocd/spokes/main.tf
- patterns/ipv6-eks-cluster/main.tf
- patterns/istio/main.tf
- patterns/karpenter-mng/main.tf
- patterns/karpenter/main.tf
- patterns/kubecost/main.tf
- patterns/ml-capacity-block/main.tf
- patterns/multi-tenancy-with-teams/main.tf
- patterns/nvidia-gpu-efa/main.tf
- patterns/private-public-ingress/main.tf
- patterns/privatelink-access/main.tf
- patterns/sso-iam-identity-center/main.tf
- patterns/sso-okta/main.tf
- patterns/stateful/main.tf
- patterns/targeted-odcr/main.tf
- patterns/tls-with-aws-pca-issuer/main.tf
- patterns/wireguard-with-cilium/main.tf
Add a filter block on the availability zones data to exclude Local Zones.
Removing version filter for Karpenter helm chart on Bottlerocket pattern.
Patterns deployments fail when Local Zones are enabled in the account. Adding filter to avoid the deployment on accounts with Local Zones enabled.
The parameter for the chart version is wrong on the Bottlerocket pattern, falling on the module default. Removing the version constraint.
> fix: Availability Zone AZs Data Source to filter Local Zones

- .pre-commit-config.yaml
- docs/cSpell_dict.txt
- patterns/ecr-pull-through-cache/ecr.tf
- patterns/ecr-pull-through-cache/variables.tf
- patterns/karpenter-mng/main.tf
- patterns/karpenter/main.tf
- Correct mis-spellings, ignore files with generated content from pre-commit checks
- 
- Closes #2012
> chore: Correct mis-spellings, ignore files with generated content from pre-commit checks

- .pre-commit-config.yaml
- patterns/fargate-serverless/README.md
- patterns/ml-capacity-block/README.md
- patterns/ml-capacity-block/eks.tf
- patterns/ml-capacity-block/helm.tf
- patterns/ml-capacity-block/main.tf
- patterns/nvidia-gpu-efa/README.md
- patterns/nvidia-gpu-efa/eks.tf
- patterns/nvidia-gpu-efa/generate-efa-nccl-test.sh
- patterns/nvidia-gpu-efa/helm.tf
- patterns/nvidia-gpu-efa/main.tf
- patterns/targeted-odcr/README.md
- patterns/targeted-odcr/eks.tf
- patterns/targeted-odcr/helm.tf
- patterns/targeted-odcr/main.tf
- Update GPU patterns to use new AL2023 NVIDIA AMI variant and latest EKS 1.31
- Update EKS module to latest minor version
- Update NVIDIA device plugin references to use latest chart and remove affinity rule; the label used on the node groups matches the [default affinity](https://github.com/NVIDIA/k8s-device-plugin/blob/cb7ff493efe60581aaf429639b860307750e4639/deployments/helm/nvidia-device-plugin/values.yaml#L79) so this is no longer required 
- Update EFA device plugin to latest version
- Add `most_recent = true` to VPC CNI plugin since new features are being added on the latest version and this will avoid trying to use a feature on an older version of the CNI
> chore: Update GPU patterns to use new AL2023 NVIDIA AMI variant and latest EKS 1.31

- docs/patterns/network/vpc-lattice.md
- patterns/aws-neuron-efa/README.md
- patterns/nvidia-gpu-efa/README.md
- patterns/vpc-lattice/README.md
- Remove link to pattern sub-directory README which is not intended to be rendered on doc site - the links are currently broken and its not shown as nested
- Update EFA results shown on NVIDIA GPU w/ EFA - perf improvements reflected in latest results
- Add titles to the code sections on the EFA patterns
- Fix bullet indention to show second order grouping
> chore: Update docs to include code section titles and updated EFA results

- docs/snippets/vpc-cni-custom-networking.md
Just a simple syntax issue in the doc example.  Just missing a single }
> docs: Fix vpc-cni-custoom-networking doc

- .github/scripts/mkdocs-hooks.py
- patterns/aws-neuron-efa/README.md
- patterns/aws-neuron-efa/eks.tf
- patterns/aws-neuron-efa/helm.tf
- patterns/ml-capacity-block/README.md
- patterns/ml-capacity-block/eks.tf
- patterns/ml-capacity-block/helm.tf
- patterns/ml-container-cache/README.md
- patterns/ml-container-cache/cache_builder.tf
- patterns/ml-container-cache/eks.tf
- patterns/ml-container-cache/helm.tf
- patterns/ml-container-cache/pod-cached.yaml
- patterns/ml-container-cache/pod-uncached.yaml
- patterns/multi-node-vllm/Dockerfile
- patterns/multi-node-vllm/README.md
- patterns/multi-node-vllm/eks.tf
- patterns/multi-node-vllm/helm.tf
- patterns/nvidia-gpu-efa/README.md
- patterns/nvidia-gpu-efa/eks.tf
- patterns/nvidia-gpu-efa/helm.tf
- patterns/targeted-odcr/README.md
- patterns/targeted-odcr/eks.tf
- patterns/targeted-odcr/helm.tf
- Update ML pattern dependencies to latest
- Fix asset path for targeted ODCR - currently the images are not rendered correctly on the site https://aws-ia.github.io/terraform-aws-eks-blueprints/patterns/machine-learning/targeted-odcr/#validate
- Remove self-managed node group from ML CBR; we want to encourage customers to use EKS managed node groups
- Ensure latest releases are used and used consistently across the ML patterns
> chore: Update ML pattern dependencies to latest

- README.md
Enable folks to find the GitLab CD Component that can wrap any EKS Blueprint.
- Resolves #2092
- Makes blueprint branch based development much easier
- enables developer IDP workflows with a completed EKS Blueprint through GitLab Environments as Code.
While this is a Doc only PR - the target component code was tested here: https://gitlab.com/guided-explorations/ci-components/working-code-examples/calling-aws-eks-blueprints-cd-component/-/pipelines
> docs: GitLab Component Reference
